/*
 * Created on 8 Dec 2016 ( Time 10:49:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.business.service.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.id.wasta.bean.TIdAwardsInformation;
import com.id.wasta.bean.jpa.TIdAwardsInformationEntitySearch;
import com.id.wasta.bean.jpa.TIdPersonalInformationEntitySearch;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TIdAwardsInformationSearchServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TIdAwardsInformationSearchServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TIdAwardsInformationEntitySearch' to 'TIdAwardsInformation'
	 * @param tIdAwardsInformationEntitySearch
	 */
	public TIdAwardsInformation mapTIdAwardsInformationEntitySearchToTIdAwardsInformation(TIdAwardsInformationEntitySearch tIdAwardsInformationEntitySearch) {
		if(tIdAwardsInformationEntitySearch == null) {
			return null;
		}

		//--- Generic mapping 
		TIdAwardsInformation tIdAwardsInformation = map(tIdAwardsInformationEntitySearch, TIdAwardsInformation.class);

		//--- Link mapping ( link to TIdPersonalInformation )
		if(tIdAwardsInformationEntitySearch.getTIdPersonalInformation() != null) {
			tIdAwardsInformation.setPiaPinKey(tIdAwardsInformationEntitySearch.getTIdPersonalInformation().getPinKey());
		}
		return tIdAwardsInformation;
	}
	
	/**
	 * Mapping from 'TIdAwardsInformation' to 'TIdAwardsInformationEntitySearch'
	 * @param tIdAwardsInformation
	 * @param tIdAwardsInformationEntitySearch
	 */
	public void mapTIdAwardsInformationToTIdAwardsInformationEntitySearch(TIdAwardsInformation tIdAwardsInformation, TIdAwardsInformationEntitySearch tIdAwardsInformationEntitySearch) {
		if(tIdAwardsInformation == null) {
			return;
		}

		//--- Generic mapping 
		map(tIdAwardsInformation, tIdAwardsInformationEntitySearch);

		//--- Link mapping ( link : tIdAwardsInformation )
		if( hasLinkToTIdPersonalInformation(tIdAwardsInformation) ) {
			TIdPersonalInformationEntitySearch tIdPersonalInformation1 = new TIdPersonalInformationEntitySearch();
			tIdPersonalInformation1.setPinKey( tIdAwardsInformation.getPiaPinKey() );
			tIdAwardsInformationEntitySearch.setTIdPersonalInformation( tIdPersonalInformation1 );
		} else {
			tIdAwardsInformationEntitySearch.setTIdPersonalInformation( null );
		}

	}
	
	/**
	 * Verify that TIdPersonalInformation id is valid.
	 * @param TIdPersonalInformation TIdPersonalInformation
	 * @return boolean
	 */
	private boolean hasLinkToTIdPersonalInformation(TIdAwardsInformation tIdAwardsInformation) {
		if(tIdAwardsInformation.getPiaPinKey() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}