/*
 * Created on 6 Nov 2016 ( Time 11:25:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.business.service;


import com.id.wasta.bean.DeleteInfoBean;

/**
 * Business Service Interface for entity TIdCityStateCountryInfoView.
 */
public interface DeleteInfoService { 

	boolean changeStatus(DeleteInfoBean deleteInfoBean);
	
}
