/*
 * Created on 8 Dec 2016 ( Time 10:49:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;


public class TIdAwardsInformationSearch implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long       piaKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
		
     private String     piaAwardName ;

		
     private Long     piaPosition  ;

		
     private String     piaPositionOthers ;

		
     private Long     piaProvidedBy ;

     private String piaProvidedByType;
		
     private String     piaProvidedByOthers ;

		
     private String     piaMonth     ;

		
     private Long       piaYear      ;

		
     private String     piaDescription ;

		
     private String     activeStatus ;

		
     private Long       lockKey      ;

		
     private Long       profileKey   ;

	// "piaPinKey" (column "pia_pin_key") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //private TIdPersonalInformationSearch tIdPersonalInformation;

   
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPiaKey( Long piaKey ) {
        this.piaKey = piaKey ;
    }
    public Long getPiaKey() {
        return this.piaKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pia_award_name ( VARCHAR ) 
    public void setPiaAwardName( String piaAwardName ) {
        this.piaAwardName = piaAwardName;
    }
    public String getPiaAwardName() {
        return this.piaAwardName;
    }

    //--- DATABASE MAPPING : pia_position ( VARCHAR ) 
    public void setPiaPosition( Long piaPosition ) {
        this.piaPosition = piaPosition;
    }
    public Long getPiaPosition() {
        return this.piaPosition;
    }

    //--- DATABASE MAPPING : pia_position_others ( VARCHAR ) 
    public void setPiaPositionOthers( String piaPositionOthers ) {
        this.piaPositionOthers = piaPositionOthers;
    }
    public String getPiaPositionOthers() {
        return this.piaPositionOthers;
    }

    //--- DATABASE MAPPING : pia_provided_by ( VARCHAR ) 
    public void setPiaProvidedBy( Long piaProvidedBy ) {
        this.piaProvidedBy = piaProvidedBy;
    }
    public Long getPiaProvidedBy() {
        return this.piaProvidedBy;
    }
    
    public String getPiaProvidedByType() {
		return piaProvidedByType;
	}
	public void setPiaProvidedByType(String piaProvidedByType) {
		this.piaProvidedByType = piaProvidedByType;
	}
	//--- DATABASE MAPPING : pia_provided_by_others ( VARCHAR ) 
    public void setPiaProvidedByOthers( String piaProvidedByOthers ) {
        this.piaProvidedByOthers = piaProvidedByOthers;
    }
    public String getPiaProvidedByOthers() {
        return this.piaProvidedByOthers;
    }

    //--- DATABASE MAPPING : pia_month ( VARCHAR ) 
    public void setPiaMonth( String piaMonth ) {
        this.piaMonth = piaMonth;
    }
    public String getPiaMonth() {
        return this.piaMonth;
    }

    //--- DATABASE MAPPING : pia_year ( BIGINT ) 
    public void setPiaYear( Long piaYear ) {
        this.piaYear = piaYear;
    }
    public Long getPiaYear() {
        return this.piaYear;
    }

    //--- DATABASE MAPPING : pia_description ( VARCHAR ) 
    public void setPiaDescription( String piaDescription ) {
        this.piaDescription = piaDescription;
    }
    public String getPiaDescription() {
        return this.piaDescription;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    /*public void setTIdPersonalInformation( TIdPersonalInformationSearch tIdPersonalInformation ) {
        this.tIdPersonalInformation = tIdPersonalInformation;
    }
    public TIdPersonalInformationSearch getTIdPersonalInformation() {
        return this.tIdPersonalInformation;
    }*/


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(piaKey);
        sb.append("]:"); 
        sb.append(piaAwardName);
        sb.append("|");
        sb.append(piaPosition);
        sb.append("|");
        sb.append(piaPositionOthers);
        sb.append("|");
        sb.append(piaProvidedBy);
        sb.append("|");
        sb.append(piaProvidedByOthers);
        sb.append("|");
        sb.append(piaMonth);
        sb.append("|");
        sb.append(piaYear);
        sb.append("|");
        sb.append(piaDescription);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 


}
