/*
 * Created on 16 Dec 2016 ( Time 13:23:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;


public class TIdDashboardTransaction implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long dtId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Long dtDmId;


    private Long dtPinKey;


    private Long lockKey;


    private Long profileKey;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setDtId( Long dtId ) {
        this.dtId = dtId ;
    }

    public Long getDtId() {
        return this.dtId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDtDmId( Long dtDmId ) {
        this.dtDmId = dtDmId;
    }
    public Long getDtDmId() {
        return this.dtDmId;
    }

    public void setDtPinKey( Long dtPinKey ) {
        this.dtPinKey = dtPinKey;
    }
    public Long getDtPinKey() {
        return this.dtPinKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(dtId);
        sb.append("|");
        sb.append(dtDmId);
        sb.append("|");
        sb.append(dtPinKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 


}
