/*
 * Created on 20 Feb 2017 ( Time 14:26:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.id.wasta.util.action.CommonConstants;

public class TIdEducationalInstitutes implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long key;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 75 )
    private String code;

    @NotNull
    @Size( min = 1, max = 240 )
    private String name;

    @NotNull
    private Long educationCountryKey;


    private Long educationStateKey;


    private Long educationCityKey;

    @NotNull
    private Long educationActiveStatusKey;

    @Size( max = 200 )
    private String educationLogo;

    @NotNull
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    private Date activeFrom;

 @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    private Date activeTo;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    @NotNull
    private Long profileKey;

    @NotNull
    private Long lockKey;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKey( Long key ) {
        this.key = key ;
    }

    public Long getKey() {
        return this.key;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setEducationCountryKey( Long educationCountryKey ) {
        this.educationCountryKey = educationCountryKey;
    }
    public Long getEducationCountryKey() {
        return this.educationCountryKey;
    }

    public void setEducationStateKey( Long educationStateKey ) {
        this.educationStateKey = educationStateKey;
    }
    public Long getEducationStateKey() {
        return this.educationStateKey;
    }

    public void setEducationCityKey( Long educationCityKey ) {
        this.educationCityKey = educationCityKey;
    }
    public Long getEducationCityKey() {
        return this.educationCityKey;
    }

    public void setEducationActiveStatusKey( Long educationActiveStatusKey ) {
        this.educationActiveStatusKey = educationActiveStatusKey;
    }
    public Long getEducationActiveStatusKey() {
        return this.educationActiveStatusKey;
    }

    public void setEducationLogo( String educationLogo ) {
        this.educationLogo = educationLogo;
    }
    public String getEducationLogo() {
        return this.educationLogo;
    }

    public void setActiveFrom( Date activeFrom ) {
        this.activeFrom = activeFrom;
    }
    public Date getActiveFrom() {
        return this.activeFrom;
    }

    public void setActiveTo( Date activeTo ) {
        this.activeTo = activeTo;
    }
    public Date getActiveTo() {
        return this.activeTo;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(key);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(educationCountryKey);
        sb.append("|");
        sb.append(educationStateKey);
        sb.append("|");
        sb.append(educationCityKey);
        sb.append("|");
        sb.append(educationActiveStatusKey);
        sb.append("|");
        sb.append(educationLogo);
        sb.append("|");
        sb.append(activeFrom);
        sb.append("|");
        sb.append(activeTo);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        return sb.toString(); 
    } 


}
