/*
 * Created on 17 Nov 2016 ( Time 19:54:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.List;

/**
 *
 * @author Telosys Tools Generator
 *
 */
public class TIdExperienceInformationSearch implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    /*private Long       pexKey       ;*/


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    /*private Long       pexCityKey   ;

    private Long       pexStateKey  ;

    private Long       pexCountryKey ;

    //private Long       pexRoleKey   ;

    private String     pexFromMonth ;

    private Long       pexFromYear  ;

    private String     pexToMonth   ;

    private Long       pexToYear    ;

    private String       pexExperienceYears ;
*/
    private String     pexCurrentlyWorking ;
/*
    private String     pexRemarks   ;

    private Long       lockKey      ;

    private String     activeStatus ;

    private Long       profileKey   ;*/

	// "pexPinKey" (column "pex_pin_key") is not defined by itself because used as FK in a link 
	// "pexDesignationKey" (column "pex_designation_key") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    //  LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    private TIdDesignationMasterSearch tIdDesignationMaster;

    private List<TIdCompanyIndustryLinkSearch> listOfTIdCompanyIndustryLinkSearch;
    
    private TIdCompanyMasterSearch tIdCompanyMaster;
    
    private TIdFunctionalAreaMasterSearch tIdFunctionalAreaMaster;
    
    /*private TIdReferenceCodesDetail tIdReferenceCodesDetail;*/
    
    /*private List<TIdPersonalInfoLinkSearch> listOfTIdPersonalInfoLink;*/
    
    private TIdCountryMasterSearch tIdCountryMasterSearch;
    
    //private TIdPersonalInformationSearch tIdPersonalInformation;
    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdExperienceInformationSearch() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
   /* public void setPexKey( Long pexKey ) {
        this.pexKey = pexKey ;
    }
    public Long getPexKey() {
        return this.pexKey;
    }*/

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pex_city_key ( BIGINT ) 
   /* public void setPexCityKey( Long pexCityKey ) {
        this.pexCityKey = pexCityKey;
    }
    public Long getPexCityKey() {
        return this.pexCityKey;
    }

    //--- DATABASE MAPPING : pex_state_key ( BIGINT ) 
    public void setPexStateKey( Long pexStateKey ) {
        this.pexStateKey = pexStateKey;
    }
    public Long getPexStateKey() {
        return this.pexStateKey;
    }

    //--- DATABASE MAPPING : pix_country_key ( BIGINT ) 
    public void setPexCountryKey( Long pexCountryKey ) {
        this.pexCountryKey = pexCountryKey;
    }
    public Long getPexCountryKey() {
        return this.pexCountryKey;
    }

    //--- DATABASE MAPPING : pex_from_month ( VARCHAR ) 
    public void setPexFromMonth( String pexFromMonth ) {
        this.pexFromMonth = pexFromMonth;
    }
    public String getPexFromMonth() {
        return this.pexFromMonth;
    }

    //--- DATABASE MAPPING : pex_from_year ( BIGINT ) 
    public void setPexFromYear( Long pexFromYear ) {
        this.pexFromYear = pexFromYear;
    }
    public Long getPexFromYear() {
        return this.pexFromYear;
    }

    //--- DATABASE MAPPING : pex_to_month ( VARCHAR ) 
    public void setPexToMonth( String pexToMonth ) {
        this.pexToMonth = pexToMonth;
    }
    public String getPexToMonth() {
        return this.pexToMonth;
    }

    //--- DATABASE MAPPING : pex_to_year ( BIGINT ) 
    public void setPexToYear( Long pexToYear ) {
        this.pexToYear = pexToYear;
    }
    public Long getPexToYear() {
        return this.pexToYear;
    }

    //--- DATABASE MAPPING : pex_experience_years ( BIGINT ) 
    public void setPexExperienceYears( String pexExperienceYears ) {
        this.pexExperienceYears = pexExperienceYears;
    }
    public String getPexExperienceYears() {
        return this.pexExperienceYears;
    }
*/
    //--- DATABASE MAPPING : pex_currently_working ( VARCHAR ) 
    public void setPexCurrentlyWorking( String pexCurrentlyWorking ) {
        this.pexCurrentlyWorking = pexCurrentlyWorking;
    }
    public String getPexCurrentlyWorking() {
        return this.pexCurrentlyWorking;
    }
/*
    //--- DATABASE MAPPING : pex_remarks ( VARCHAR ) 
    public void setPexRemarks( String pexRemarks ) {
        this.pexRemarks = pexRemarks;
    }
    public String getPexRemarks() {
        return this.pexRemarks;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }*/


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTIdDesignationMaster( TIdDesignationMasterSearch tIdDesignationMaster ) {
        this.tIdDesignationMaster = tIdDesignationMaster;
    }
    public TIdDesignationMasterSearch getTIdDesignationMaster() {
        return this.tIdDesignationMaster;
    }

    public void setTIdCompanyMaster( TIdCompanyMasterSearch tIdCompanyMaster ) {
        this.tIdCompanyMaster = tIdCompanyMaster;
    }
    public TIdCompanyMasterSearch getTIdCompanyMaster() {
        return this.tIdCompanyMaster;
    }
    
    public void setTIdFunctionalAreaMaster( TIdFunctionalAreaMasterSearch tIdFunctionalAreaMaster ) {
        this.tIdFunctionalAreaMaster = tIdFunctionalAreaMaster;
    }
    public TIdFunctionalAreaMasterSearch getTIdFunctionalAreaMaster() {
        return this.tIdFunctionalAreaMaster;
    }
    
    
    
    
    /*public TIdPersonalInformationSearch getTIdPersonalInformation() {
		return tIdPersonalInformation;
	}

	public void setTIdPersonalInformation(
			TIdPersonalInformationSearch tIdPersonalInformation) {
		this.tIdPersonalInformation = tIdPersonalInformation;
	}*/

	/*public TIdReferenceCodesDetail getTIdReferenceCodesDetail() {
		return tIdReferenceCodesDetail;
	}

	public void setTIdReferenceCodesDetail(
			TIdReferenceCodesDetail tIdReferenceCodesDetail) {
		this.tIdReferenceCodesDetail = tIdReferenceCodesDetail;
	}*/

	public List<TIdCompanyIndustryLinkSearch> getListOfTIdCompanyIndustryLinkSearch() {
		return listOfTIdCompanyIndustryLinkSearch;
	}

	public void setListOfTIdCompanyIndustryLinkSearch(
			List<TIdCompanyIndustryLinkSearch> listOfTIdCompanyIndustryLinkSearch) {
		this.listOfTIdCompanyIndustryLinkSearch = listOfTIdCompanyIndustryLinkSearch;
	}
	
	/*public List<TIdPersonalInfoLinkSearch> getListOfTIdPersonalInfoLink() {
		return listOfTIdPersonalInfoLink;
	}

	public void setListOfTIdPersonalInfoLink(
			List<TIdPersonalInfoLinkSearch> listOfTIdPersonalInfoLink) {
		this.listOfTIdPersonalInfoLink = listOfTIdPersonalInfoLink;
	}*/
	
	public TIdCountryMasterSearch gettIdCountryMasterSearch() {
		return tIdCountryMasterSearch;
	}

	public void settIdCountryMasterSearch(TIdCountryMasterSearch tIdCountryMasterSearch) {
		this.tIdCountryMasterSearch = tIdCountryMasterSearch;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    /*public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pexKey);
        sb.append("]:"); 
        sb.append(pexCityKey);
        sb.append("|");
        sb.append(pexStateKey);
        sb.append("|");
        sb.append(pexCountryKey);
        sb.append("|");
        sb.append(pexFromMonth);
        sb.append("|");
        sb.append(pexFromYear);
        sb.append("|");
        sb.append(pexToMonth);
        sb.append("|");
        sb.append(pexToYear);
        sb.append("|");
        sb.append(pexExperienceYears);
        sb.append("|");
        sb.append(pexCurrentlyWorking);
        sb.append("|");
        sb.append(pexRemarks);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } */

}
