/*
 * Created on 13 Nov 2017 ( Time 18:26:39 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.id.wasta.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class TIdEtUserPasswordResetLink implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long uprlId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long uprlUserId;

    @NotNull
    @Size( min = 1, max = 200 )
    private String uprlPasswordLink;

    @NotNull
    private Long profileKey;

    @NotNull
    private Long lockKey;

    @NotNull
    private Long activeStatus;

    @NotNull
    private Date modifiedOn;


    private Boolean uprlLinkActive;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUprlId( Long uprlId ) {
        this.uprlId = uprlId ;
    }

    public Long getUprlId() {
        return this.uprlId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUprlUserId( Long uprlUserId ) {
        this.uprlUserId = uprlUserId;
    }
    public Long getUprlUserId() {
        return this.uprlUserId;
    }

    public void setUprlPasswordLink( String uprlPasswordLink ) {
        this.uprlPasswordLink = uprlPasswordLink;
    }
    public String getUprlPasswordLink() {
        return this.uprlPasswordLink;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setActiveStatus( Long activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public Long getActiveStatus() {
        return this.activeStatus;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setUprlLinkActive( Boolean uprlLinkActive ) {
        this.uprlLinkActive = uprlLinkActive;
    }
    public Boolean getUprlLinkActive() {
        return this.uprlLinkActive;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(uprlId);
        sb.append("|");
        sb.append(uprlUserId);
        sb.append("|");
        sb.append(uprlPasswordLink);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(uprlLinkActive);
        return sb.toString(); 
    } 


}
