/*
 * Created on 12 Feb 2019 ( Time 18:12:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean;

import java.io.Serializable;

/**
 * Persistent class for entity stored in table "t_id_landing_master"
 *
 * @author Telosys Tools Generator
 *
 */

public class TIdLandingMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       lmKey        ;

    private Long       lmPinKey     ;
    
    private Long 	   lmNewContact;

    private Long       lmEmail      ;

    private Long       lmPhoneNo    ;

    private Long       lmHome       ;

    private Long       lmDiscussionDtls ;

    private Long       lmBusinessPotential ;

    private Long       lmAddPotential ;

    private Long       lmRecreation ;

    private Long       lmPersonalInfo ;

    private Long       lmPersonalInterest ;

    private Long       lmProfessionalInterest ;

    private Long       lmPersonalPriorities ;

    private Long       lmExperience ;

    private Long       lmEducation  ;

    private Long       lmProjectExecuted ;

    private Long       lmProfessionalExpertise ;

    private Long       lmAwardsRecognition ;

    private Long       lmAddInformation ;

    private Long       lmPersonalRelationships ;

    private Long       lmProfessionalRelationship ;

    private Long       lockKey      ;

    private Long       profileKey   ;

    private Long       unReadContacts;

    private Long contact;
    
    private Long team;
    
    private Long notification;
    
    private Long myContact;
    
    private Long favorite;
    
    private Long newUpdate;
    
    private Long traceable;
    
    private Long nonTraceable;

    public TIdLandingMaster() {
		super();
		this.lmNewContact=0L;
		this.lmEmail=0L;
		this.lmPhoneNo=0L;
		this.lmHome=0L;
		this.lmDiscussionDtls=0L;
		this.lmBusinessPotential=0L;
		this.lmAddPotential=0L;
		this.lmRecreation=0L;
		this.lmPersonalInfo=0L;
		this.lmPersonalInterest=0L;
		this.lmProfessionalInterest=0L;
		this.lmPersonalPriorities=0L;
		this.lmExperience=0L;
		this.lmEducation=0L;
		this.lmProjectExecuted=0L;
		this.lmProfessionalExpertise=0L;
		this.lmAwardsRecognition=0L;
		this.lmAddInformation=0L;
		this.lmPersonalRelationships=0L;
		this.lmProfessionalRelationship=0L;
		this.unReadContacts=0L;
		this.team=0L;
		this.notification=0L;
		this.myContact=0L;
		this.favorite=0L;
		this.newUpdate=0L;
		this.traceable=0L;
		this.nonTraceable=0L;
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLmKey( Long lmKey ) {
        this.lmKey = lmKey ;
    }
    public Long getLmKey() {
        return this.lmKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setLmPinKey( Long lmPinKey ) {
        this.lmPinKey = lmPinKey;
    }
    public Long getLmPinKey() {
        return this.lmPinKey;
    }
    
    public Long getLmNewContact() {
		return lmNewContact;
	}
	public void setLmNewContact(Long lmNewContact) {
		this.lmNewContact = lmNewContact;
	}

	public void setLmEmail( Long lmEmail ) {
        this.lmEmail = lmEmail;
    }
    public Long getLmEmail() {
        return this.lmEmail;
    }

    public void setLmPhoneNo( Long lmPhoneNo ) {
        this.lmPhoneNo = lmPhoneNo;
    }
    public Long getLmPhoneNo() {
        return this.lmPhoneNo;
    }

    public void setLmHome( Long lmHome ) {
        this.lmHome = lmHome;
    }
    public Long getLmHome() {
        return this.lmHome;
    }

    public void setLmDiscussionDtls( Long lmDiscussionDtls ) {
        this.lmDiscussionDtls = lmDiscussionDtls;
    }
    public Long getLmDiscussionDtls() {
        return this.lmDiscussionDtls;
    }

    public void setLmBusinessPotential( Long lmBusinessPotential ) {
        this.lmBusinessPotential = lmBusinessPotential;
    }
    public Long getLmBusinessPotential() {
        return this.lmBusinessPotential;
    }

    public void setLmAddPotential( Long lmAddPotential ) {
        this.lmAddPotential = lmAddPotential;
    }
    public Long getLmAddPotential() {
        return this.lmAddPotential;
    }

    public void setLmRecreation( Long lmRecreation ) {
        this.lmRecreation = lmRecreation;
    }
    public Long getLmRecreation() {
        return this.lmRecreation;
    }

    public void setLmPersonalInfo( Long lmPersonalInfo ) {
        this.lmPersonalInfo = lmPersonalInfo;
    }
    public Long getLmPersonalInfo() {
        return this.lmPersonalInfo;
    }

    public void setLmPersonalInterest( Long lmPersonalInterest ) {
        this.lmPersonalInterest = lmPersonalInterest;
    }
    public Long getLmPersonalInterest() {
        return this.lmPersonalInterest;
    }

    public void setLmProfessionalInterest( Long lmProfessionalInterest ) {
        this.lmProfessionalInterest = lmProfessionalInterest;
    }
    public Long getLmProfessionalInterest() {
        return this.lmProfessionalInterest;
    }

    public void setLmPersonalPriorities( Long lmPersonalPriorities ) {
        this.lmPersonalPriorities = lmPersonalPriorities;
    }
    public Long getLmPersonalPriorities() {
        return this.lmPersonalPriorities;
    }

    public void setLmExperience( Long lmExperience ) {
        this.lmExperience = lmExperience;
    }
    public Long getLmExperience() {
        return this.lmExperience;
    }

    public void setLmEducation( Long lmEducation ) {
        this.lmEducation = lmEducation;
    }
    public Long getLmEducation() {
        return this.lmEducation;
    }

    public void setLmProjectExecuted( Long lmProjectExecuted ) {
        this.lmProjectExecuted = lmProjectExecuted;
    }
    public Long getLmProjectExecuted() {
        return this.lmProjectExecuted;
    }

    public void setLmProfessionalExpertise( Long lmProfessionalExpertise ) {
        this.lmProfessionalExpertise = lmProfessionalExpertise;
    }
    public Long getLmProfessionalExpertise() {
        return this.lmProfessionalExpertise;
    }

    public void setLmAwardsRecognition( Long lmAwardsRecognition ) {
        this.lmAwardsRecognition = lmAwardsRecognition;
    }
    public Long getLmAwardsRecognition() {
        return this.lmAwardsRecognition;
    }

    public void setLmAddInformation( Long lmAddInformation ) {
        this.lmAddInformation = lmAddInformation;
    }
    public Long getLmAddInformation() {
        return this.lmAddInformation;
    }

    public void setLmPersonalRelationships( Long lmPersonalRelationships ) {
        this.lmPersonalRelationships = lmPersonalRelationships;
    }
    public Long getLmPersonalRelationships() {
        return this.lmPersonalRelationships;
    }

    public void setLmProfessionalRelationship( Long lmProfessionalRelationship ) {
        this.lmProfessionalRelationship = lmProfessionalRelationship;
    }
    public Long getLmProfessionalRelationship() {
        return this.lmProfessionalRelationship;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }
    
    public Long getUnReadContacts() {
		return unReadContacts;
	}
	public void setUnReadContacts(Long unReadContacts) {
		this.unReadContacts = unReadContacts;
	}	

	public Long getContact() {
		return contact;
	}

	public void setContact(Long contact) {
		this.contact = contact;
	}

	public Long getTeam() {
		return team;
	}

	public void setTeam(Long team) {
		this.team = team;
	}

	public Long getNotification() {
		return notification;
	}

	public void setNotification(Long notification) {
		this.notification = notification;
	}

	public Long getMyContact() {
		return myContact;
	}

	public void setMyContact(Long myContact) {
		this.myContact = myContact;
	}

	public Long getFavorite() {
		return favorite;
	}

	public void setFavorite(Long favorite) {
		this.favorite = favorite;
	}

	public Long getNewUpdate() {
		return newUpdate;
	}

	public void setNewUpdate(Long newUpdate) {
		this.newUpdate = newUpdate;
	}

	public Long getTraceable() {
		return traceable;
	}

	public void setTraceable(Long traceable) {
		this.traceable = traceable;
	}

	public Long getNonTraceable() {
		return nonTraceable;
	}

	public void setNonTraceable(Long nonTraceable) {
		this.nonTraceable = nonTraceable;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(lmKey);
        sb.append("]:"); 
        sb.append(lmPinKey);
        sb.append("|");
        sb.append(lmNewContact);
        sb.append("|");
        sb.append(lmEmail);
        sb.append("|");
        sb.append(lmPhoneNo);
        sb.append("|");
        sb.append(lmHome);
        sb.append("|");
        sb.append(lmDiscussionDtls);
        sb.append("|");
        sb.append(lmBusinessPotential);
        sb.append("|");
        sb.append(lmAddPotential);
        sb.append("|");
        sb.append(lmRecreation);
        sb.append("|");
        sb.append(lmPersonalInfo);
        sb.append("|");
        sb.append(lmPersonalInterest);
        sb.append("|");
        sb.append(lmProfessionalInterest);
        sb.append("|");
        sb.append(lmPersonalPriorities);
        sb.append("|");
        sb.append(lmExperience);
        sb.append("|");
        sb.append(lmEducation);
        sb.append("|");
        sb.append(lmProjectExecuted);
        sb.append("|");
        sb.append(lmProfessionalExpertise);
        sb.append("|");
        sb.append(lmAwardsRecognition);
        sb.append("|");
        sb.append(lmAddInformation);
        sb.append("|");
        sb.append(lmPersonalRelationships);
        sb.append("|");
        sb.append(lmProfessionalRelationship);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(contact);
        sb.append("|");
        sb.append(team);
        sb.append("|");
        sb.append(notification);
        sb.append("|");
        sb.append(myContact);
        sb.append("|");
        sb.append(favorite);
        sb.append("|");
        sb.append(newUpdate);
        sb.append("|");
        sb.append(traceable);
        sb.append("|");
        sb.append(nonTraceable);
        return sb.toString(); 
    } 

}
