/*
 * Created on 1 Nov 2016 ( Time 10:40:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean;

import java.io.Serializable;

 
public class TIdPersonalInfoLink implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long pilKey;

	private Long pilPinKey;

	private Long pilPexKey;

	private String pilCurrentlyWorking;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public TIdPersonalInfoLink() {
		super();
	}

	public Long getPilKey() {
		return pilKey;
	}

	public void setPilKey(Long pilKey) {
		this.pilKey = pilKey;
	}

	public Long getPilPinKey() {
		return pilPinKey;
	}

	public void setPilPinKey(Long pilPinKey) {
		this.pilPinKey = pilPinKey;
	}

	public Long getPilPexKey() {
		return pilPexKey;
	}

	public void setPilPexKey(Long pilPexKey) {
		this.pilPexKey = pilPexKey;
	}

	public String getPilCurrentlyWorking() {
		return pilCurrentlyWorking;
	}

	public void setPilCurrentlyWorking(String pilCurrentlyWorking) {
		this.pilCurrentlyWorking = pilCurrentlyWorking;
	}

}
