
/*
 * Created on 28 Aug 2017 ( Time 18:06:30 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

//import org.hibernate.validator.constraints.* ;

public class TIdProgAccessFieldsMaster implements Serializable {

	private static final long serialVersionUID = 1L;

	@NotNull
	private Long key;

	@NotNull
	private Long pafmPabmKey;

	@NotNull
	@Size(min = 1, max = 300)
	private String name;

	@NotNull
	@Size(min = 1, max = 90)
	private String code;

	@NotNull
	@Size(min = 1, max = 225)
	private String activeStatus;

	@NotNull
	private Long lockKey;

	@NotNull
	private Long profileKey;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : pafm_key ( BIGINT )
	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	// --- DATABASE MAPPING : pafm_pabm_key ( BIGINT )
	public void setPafmPabmKey(Long pafmPabmKey) {
		this.pafmPabmKey = pafmPabmKey;
	}

	public Long getPafmPabmKey() {
		return this.pafmPabmKey;
	}

	// --- DATABASE MAPPING : pafm_field_name ( VARCHAR )
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	// --- DATABASE MAPPING : pafm_column_id ( VARCHAR )
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// --- DATABASE MAPPING : active_status ( VARCHAR )
	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	public String getActiveStatus() {
		return this.activeStatus;
	}

	// --- DATABASE MAPPING : lock_key ( BIGINT )
	public void setLockKey(Long lockKey) {
		this.lockKey = lockKey;
	}

	public Long getLockKey() {
		return this.lockKey;
	}

	// --- DATABASE MAPPING : profile_key ( BIGINT )
	public void setProfileKey(Long profileKey) {
		this.profileKey = profileKey;
	}

	public Long getProfileKey() {
		return this.profileKey;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append("]:");
		sb.append(key);
		sb.append("|");
		sb.append(pafmPabmKey);
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(code);
		sb.append("|");
		sb.append(activeStatus);
		sb.append("|");
		sb.append(lockKey);
		sb.append("|");
		sb.append(profileKey);
		return sb.toString();
	}

}
