/*
 * Created on 22 Feb 2017 ( Time 14:29:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class TIdProfessionalInterestsView implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long key;

    @NotNull
    private Long priPinKey;

    @NotNull
    private Long priSkillKey;

    @Size( max = 75 )
    private String priOthers;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    @NotNull
    private Long profileKey;

    @NotNull
    private Long lockKey;


    private Long pinKey;

    @Size( max = 240 )
    private String name;


    private Long skillCategory;

    private boolean viewAccessFlag = true;
    
    private String priSkillStatus;
    
    private Long priCreatedBy;
    
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setKey( Long key ) {
        this.key = key;
    }
    public Long getKey() {
        return this.key;
    }

    public void setPriPinKey( Long priPinKey ) {
        this.priPinKey = priPinKey;
    }
    public Long getPriPinKey() {
        return this.priPinKey;
    }

    public void setPriSkillKey( Long priSkillKey ) {
        this.priSkillKey = priSkillKey;
    }
    public Long getPriSkillKey() {
        return this.priSkillKey;
    }

    public void setPriOthers( String priOthers ) {
        this.priOthers = priOthers;
    }
    public String getPriOthers() {
        return this.priOthers;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setPinKey( Long pinKey ) {
        this.pinKey = pinKey;
    }
    public Long getPinKey() {
        return this.pinKey;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setSkillCategory( Long skillCategory ) {
        this.skillCategory = skillCategory;
    }
    public Long getSkillCategory() {
        return this.skillCategory;
    }

    public boolean isViewAccessFlag() {
		return viewAccessFlag;
	}
	public void setViewAccessFlag(boolean viewAccessFlag) {
		this.viewAccessFlag = viewAccessFlag;
	}
	
	public String getPriSkillStatus() {
		return priSkillStatus;
	}

	public void setPriSkillStatus(String priSkillStatus) {
		this.priSkillStatus = priSkillStatus;
	}
	
	public Long getPriCreatedBy() {
		return priCreatedBy;
	}
	public void setPriCreatedBy(Long priCreatedBy) {
		this.priCreatedBy = priCreatedBy;
	}
		
	
    
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        
	
		public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(key);
        sb.append("|");
        sb.append(priPinKey);
        sb.append("|");
        sb.append(priSkillKey);
        sb.append("|");
        sb.append(priOthers);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(pinKey);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(skillCategory);
        sb.append("|");
        sb.append(priSkillStatus);
        sb.append("|");
        sb.append(priSkillStatus);
        
        sb.append("|");
        sb.append(priCreatedBy);
        
        return sb.toString(); 
    } 


}
