/*
 * Created on 4 Nov 2016 ( Time 12:24:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.id.wasta.util.action.CommonConstants;

public class TIdPersonalInformation implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long pinKey;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long pinTitle;

    @NotNull
    @Size( min = 1, max = 75 )
    private String pinFirstName;

    @Size( max = 75 )
    private String pinLastName;

    @Size( max = 75 )
    private String pinNickName;

    @NotNull
    @Size( min = 1, max = 1 )
    private String pinGender;


    private Long pinNationalityKey;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    private Date pinDob;
    
    private String pinDobStr;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
	private Date       pinDoa       ;

    @Size( max = 75 )
    private String pinEmail;

    @Size( max = 500 )
    private String pinAddress;


    private Long pinCityKey;


    private Long pinStateKey;


    private Long pinCountryKey;

    @Size( max = 1000 )
    private String pinRemarks;

    private Long pinCreatorKey;
    
    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    @NotNull
    private Long profileKey;

    @NotNull
    private Long lockKey;
    
    private Date modifiedOn;
    private Long pinParentKey;
    
    private Long pinPercentage;
	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPinKey( Long pinKey ) {
        this.pinKey = pinKey ;
    }

    public Long getPinKey() {
        return this.pinKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPinTitle( Long pinTitle ) {
        this.pinTitle = pinTitle;
    }
    public Long getPinTitle() {
        return this.pinTitle;
    }
    
    public Long getPinParentKey() {
		return pinParentKey;
	}

	public void setPinParentKey(Long pinParentKey) {
		this.pinParentKey = pinParentKey;
	}

	public void setPinFirstName( String pinFirstName ) {
        this.pinFirstName = pinFirstName;
    }
    public String getPinFirstName() {
        return this.pinFirstName;
    }

    public void setPinLastName( String pinLastName ) {
        this.pinLastName = pinLastName;
    }
    public String getPinLastName() {
        return this.pinLastName;
    }

    public void setPinNickName( String pinNickName ) {
        this.pinNickName = pinNickName;
    }
    public String getPinNickName() {
        return this.pinNickName;
    }

    public void setPinGender( String pinGender ) {
        this.pinGender = pinGender;
    }
    public String getPinGender() {
        return this.pinGender;
    }

    public void setPinNationalityKey( Long pinNationalityKey ) {
        this.pinNationalityKey = pinNationalityKey;
    }
    public Long getPinNationalityKey() {
        return this.pinNationalityKey;
    }

    public void setPinDob( Date pinDob ) {
        this.pinDob = pinDob;
    }
    public Date getPinDob() {
        return this.pinDob;
    }

    public void setPinEmail( String pinEmail ) {
        this.pinEmail = pinEmail;
    }
    public String getPinEmail() {
        return this.pinEmail;
    }

    public void setPinAddress( String pinAddress ) {
        this.pinAddress = pinAddress;
    }
    public String getPinAddress() {
        return this.pinAddress;
    }

    public void setPinCityKey( Long pinCityKey ) {
        this.pinCityKey = pinCityKey;
    }
    public Long getPinCityKey() {
        return this.pinCityKey;
    }

    public void setPinStateKey( Long pinStateKey ) {
        this.pinStateKey = pinStateKey;
    }
    public Long getPinStateKey() {
        return this.pinStateKey;
    }

    public void setPinCountryKey( Long pinCountryKey ) {
        this.pinCountryKey = pinCountryKey;
    }
    public Long getPinCountryKey() {
        return this.pinCountryKey;
    }

    public void setPinRemarks( String pinRemarks ) {
        this.pinRemarks = pinRemarks;
    }
    public String getPinRemarks() {
        return this.pinRemarks;
    }
    
    public Long getPinCreatorKey() {
		return pinCreatorKey;
	}
	public void setPinCreatorKey(Long pinCreatorKey) {
		this.pinCreatorKey = pinCreatorKey;
	}

	public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }
    
    public Date getModifiedOn() {
		return modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getPinDobStr() {
		return pinDobStr;
	}
	public void setPinDobStr(String pinDobStr) {
		this.pinDobStr = pinDobStr;
	}
	
	public Date getPinDoa() {
		return pinDoa;
	}
	public void setPinDoa(Date pinDoa) {
		this.pinDoa = pinDoa;
	}
	


	public Long getPinPercentage() {
		return pinPercentage;
	}

	public void setPinPercentage(Long pinPercentage) {
		this.pinPercentage = pinPercentage;
	}
	
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
    

		@Override
		public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(pinKey);
        sb.append("|");
        sb.append(pinTitle);
        sb.append("|");
        sb.append(pinFirstName);
        sb.append("|");
        sb.append(pinLastName);
        sb.append("|");
        sb.append(pinNickName);
        sb.append("|");
        sb.append(pinGender);
        sb.append("|");
        sb.append(pinNationalityKey);
        sb.append("|");
        sb.append(pinDob);
        sb.append("|");
        sb.append(pinEmail);
        sb.append("|");
        sb.append(pinAddress);
        sb.append("|");
        sb.append(pinCityKey);
        sb.append("|");
        sb.append(pinStateKey);
        sb.append("|");
        sb.append(pinCountryKey);
        sb.append("|");
        sb.append(pinRemarks);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(pinDobStr);
        sb.append("|");
        sb.append(pinPercentage);
        return sb.toString(); 
    } 


}
