/*
 * Created on 20 Feb 2017 ( Time 18:45:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class TIdPersonalInterests implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long key;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long periPinKey;

    @NotNull
    private Long periSkillKey;

    @Size( max = 75 )
    private String periOthers;

    @NotNull
    private Long profileKey;

    @NotNull
    private Long lockKey;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    private Long otherSkillKey;
    
    private String otherSkillName;
    
    private String auditJson;
    
    private Long periCreatedBy;
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKey( Long key ) {
        this.key = key ;
    }

    public Long getKey() {
        return this.key;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPeriPinKey( Long periPinKey ) {
        this.periPinKey = periPinKey;
    }
    public Long getPeriPinKey() {
        return this.periPinKey;
    }

    public void setPeriSkillKey( Long periSkillKey ) {
        this.periSkillKey = periSkillKey;
    }
    public Long getPeriSkillKey() {
        return this.periSkillKey;
    }

    public void setPeriOthers( String periOthers ) {
        this.periOthers = periOthers;
    }
    public String getPeriOthers() {
        return this.periOthers;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public Long getOtherSkillKey() {
		return otherSkillKey;
	}

	public void setOtherSkillKey(Long otherSkillKey) {
		this.otherSkillKey = otherSkillKey;
	}

	public String getOtherSkillName() {
		return otherSkillName;
	}

	public void setOtherSkillName(String otherSkillName) {
		this.otherSkillName = otherSkillName;
	}

	public String getAuditJson() {
		return auditJson;
	}

	public void setAuditJson(String auditJson) {
		this.auditJson = auditJson;
	}
	
	

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
    public Long getPeriCreatedBy() {
		return periCreatedBy;
	}

	public void setPeriCreatedBy(Long periCreatedBy) {
		this.periCreatedBy = periCreatedBy;
	}

	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(key);
        sb.append("|");
        sb.append(periPinKey);
        sb.append("|");
        sb.append(periSkillKey);
        sb.append("|");
        sb.append(periOthers);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(periCreatedBy);
        
        return sb.toString(); 
    }

}
