/*
 * Created on 7 Feb 2017 ( Time 18:03:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class TIdProjectsInformationView implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long pipKey;

    @NotNull
    private Long pipPinKey;

    @NotNull
    @Size( min = 1, max = 240 )
    private String pipProjectName;


    private Long pipCompanyCmsKey;

    @Size( max = 3 )
    private String pipFromMonth;


    private Long pipFromYear;

    @Size( max = 10 )
    private String pipToMonth;


    private Long pipToYear;

    @Size( max = 10 )
    private String pipYears;

    @Size( max = 1000 )
    private String pipDescription;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    @NotNull
    private Long lockKey;

    @NotNull
    private Long profileKey;


    private Long videoCount;


    private Long imageCount;


    private Long docCount;
    
    private String companyCode;
    
    private String companyName;

    private boolean viewAccessFlag = true;
    
    private String pipCompanyCmsStatus;
    
    
    private Long pipCreatedBy;

    public String getPipCompanyCmsStatus() {
		return pipCompanyCmsStatus;
	}

	public void setPipCompanyCmsStatus(String pipCompanyCmsStatus) {
		this.pipCompanyCmsStatus = pipCompanyCmsStatus;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPipKey( Long pipKey ) {
        this.pipKey = pipKey;
    }
    public Long getPipKey() {
        return this.pipKey;
    }

    public void setPipPinKey( Long pipPinKey ) {
        this.pipPinKey = pipPinKey;
    }
    public Long getPipPinKey() {
        return this.pipPinKey;
    }

    public void setPipProjectName( String pipProjectName ) {
        this.pipProjectName = pipProjectName;
    }
    public String getPipProjectName() {
        return this.pipProjectName;
    }

    public void setPipCompanyCmsKey( Long pipCompanyCmsKey ) {
        this.pipCompanyCmsKey = pipCompanyCmsKey;
    }
    public Long getPipCompanyCmsKey() {
        return this.pipCompanyCmsKey;
    }

    public void setPipFromMonth( String pipFromMonth ) {
        this.pipFromMonth = pipFromMonth;
    }
    public String getPipFromMonth() {
        return this.pipFromMonth;
    }

    public void setPipFromYear( Long pipFromYear ) {
        this.pipFromYear = pipFromYear;
    }
    public Long getPipFromYear() {
        return this.pipFromYear;
    }

    public void setPipToMonth( String pipToMonth ) {
        this.pipToMonth = pipToMonth;
    }
    public String getPipToMonth() {
        return this.pipToMonth;
    }

    public void setPipToYear( Long pipToYear ) {
        this.pipToYear = pipToYear;
    }
    public Long getPipToYear() {
        return this.pipToYear;
    }

    public void setPipYears( String pipYears ) {
        this.pipYears = pipYears;
    }
    public String getPipYears() {
        return this.pipYears;
    }

    public void setPipDescription( String pipDescription ) {
        this.pipDescription = pipDescription;
    }
    public String getPipDescription() {
        return this.pipDescription;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setVideoCount( Long videoCount ) {
        this.videoCount = videoCount;
    }
    public Long getVideoCount() {
        return this.videoCount;
    }

    public void setImageCount( Long imageCount ) {
        this.imageCount = imageCount;
    }
    public Long getImageCount() {
        return this.imageCount;
    }

    public void setDocCount( Long docCount ) {
        this.docCount = docCount;
    }
    public Long getDocCount() {
        return this.docCount;
    }

    public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	
	public boolean isViewAccessFlag() {
		return viewAccessFlag;
	}
	public void setViewAccessFlag(boolean viewAccessFlag) {
		this.viewAccessFlag = viewAccessFlag;
	}
	
	

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
	public Long getPipCreatedBy() {
		return pipCreatedBy;
	}

	public void setPipCreatedBy(Long pipCreatedBy) {
		this.pipCreatedBy = pipCreatedBy;
	}

	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(pipKey);
        sb.append("|");
        sb.append(pipPinKey);
        sb.append("|");
        sb.append(pipProjectName);
        sb.append("|");
        sb.append(pipCompanyCmsKey);
        sb.append("|");
        sb.append(pipFromMonth);
        sb.append("|");
        sb.append(pipFromYear);
        sb.append("|");
        sb.append(pipToMonth);
        sb.append("|");
        sb.append(pipToYear);
        sb.append("|");
        sb.append(pipYears);
        sb.append("|");
        sb.append(pipDescription);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(videoCount);
        sb.append("|");
        sb.append(imageCount);
        sb.append("|");
        sb.append(docCount);
        sb.append("|");
        sb.append(pipCompanyCmsStatus);
        sb.append("|");
        sb.append(pipCreatedBy);
        
        return sb.toString(); 
    } 


}
