/*
 * Created on 20 Feb 2017 ( Time 10:26:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class TIdRelationGroupInfoView implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long prlKey;

    @NotNull
    private Long prlPinKey;

    @Size( max = 65535 )
    private String relationshipGroupName;


    private Long rcdOrderBy;

    @Size( max = 20 )
    private String relationtype;

    @Size( max = 20 )
    private String relationship;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;

    private boolean viewAccessFlag = true; 

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPrlKey( Long prlKey ) {
        this.prlKey = prlKey;
    }
    public Long getPrlKey() {
        return this.prlKey;
    }

    public void setPrlPinKey( Long prlPinKey ) {
        this.prlPinKey = prlPinKey;
    }
    public Long getPrlPinKey() {
        return this.prlPinKey;
    }

    public void setrRelationshipGroupName( String relationshipGroupName ) {
        this.relationshipGroupName = relationshipGroupName;
    }
    public String getRelationshipGroupName() {
        return this.relationshipGroupName;
    }

    public void setRcdOrderBy( Long rcdOrderBy ) {
        this.rcdOrderBy = rcdOrderBy;
    }
    public Long getRcdOrderBy() {
        return this.rcdOrderBy;
    }

    public void setRelationtype( String relationtype ) {
        this.relationtype = relationtype;
    }
    public String getRelationtype() {
        return this.relationtype;
    }

    public void setRelationship( String relationship ) {
        this.relationship = relationship;
    }
    public String getRelationship() {
        return this.relationship;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    public boolean isViewAccessFlag() {
		return viewAccessFlag;
	}
	public void setViewAccessFlag(boolean viewAccessFlag) {
		this.viewAccessFlag = viewAccessFlag;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(prlKey);
        sb.append("|");
        sb.append(prlPinKey);
        // attribute 'prlFirstName' not usable (type = String Long Text)
        sb.append("|");
        sb.append(rcdOrderBy);
        sb.append("|");
        sb.append(relationtype);
        sb.append("|");
        sb.append(relationship);
        sb.append("|");
        sb.append(activeStatus);
        return sb.toString(); 
    } 


}
