/*
 * Created on 1 Nov 2016 ( Time 10:41:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class TIdSocialMediaInformation implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long psmKey;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long psmPinKey;

    @NotNull
    @Size( min = 1, max = 1 )
    private String psmType;

    @NotNull
    @Size( min = 1, max = 75 )
    private String psmId;

    @NotNull
    private Long lockKey;

    @NotNull
    private Long profileKey;

    @NotNull
    @Size( min = 1, max = 75 )
    private String activeStatus;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPsmKey( Long psmKey ) {
        this.psmKey = psmKey ;
    }

    public Long getPsmKey() {
        return this.psmKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPsmPinKey( Long psmPinKey ) {
        this.psmPinKey = psmPinKey;
    }
    public Long getPsmPinKey() {
        return this.psmPinKey;
    }

    public void setPsmType( String psmType ) {
        this.psmType = psmType;
    }
    public String getPsmType() {
        return this.psmType;
    }

    public void setPsmId( String psmId ) {
        this.psmId = psmId;
    }
    public String getPsmId() {
        return this.psmId;
    }

    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(psmKey);
        sb.append("|");
        sb.append(psmPinKey);
        sb.append("|");
        sb.append(psmType);
        sb.append("|");
        sb.append(psmId);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(activeStatus);
        return sb.toString(); 
    } 


}
