/*
 * Created on 13 Nov 2016 ( Time 16:25:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.id.wasta.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.id.wasta.util.action.CommonConstants;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIdTableAuditLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long tauditKey;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 225 )
    private String tauditTableName;

    @Size( max = 3 )
    private String tauditRecordType;

    @Size( max = 720 )
    private String tauditKeyName1;


    private Long tauditKeyValue1;

    @Size( max = 720 )
    private String tauditKeyName2;


    private Long tauditKeyValue2;

    @Size( max = 720 )
    private String tauditKeyName3;


    private Long tauditKeyValue3;

    @Size( max = 720 )
    private String tauditKeyName4;


    private Long tauditKeyValue4;

    @Size( max = 720 )
    private String tauditKeyName5;


    private Long tauditKeyValue5;

    @NotNull
    private Long tauditActionBy;

    @NotNull
    @Size( min = 1, max = 25 )
    private String tauditActionName;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    private Date tauditActionOn;

    @Size( max = 720 )
    private String tauditActionIp;

    @Size( max = 12000 )
    private String tauditNotes;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @NotNull
    private Date tauditTimeStamp;

    @NotNull
    private Long tauditLockKey;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTauditKey( Long tauditKey ) {
        this.tauditKey = tauditKey ;
    }

    public Long getTauditKey() {
        return this.tauditKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTauditTableName( String tauditTableName ) {
        this.tauditTableName = tauditTableName;
    }
    public String getTauditTableName() {
        return this.tauditTableName;
    }

    public void setTauditRecordType( String tauditRecordType ) {
        this.tauditRecordType = tauditRecordType;
    }
    public String getTauditRecordType() {
        return this.tauditRecordType;
    }

    public void setTauditKeyName1( String tauditKeyName1 ) {
        this.tauditKeyName1 = tauditKeyName1;
    }
    public String getTauditKeyName1() {
        return this.tauditKeyName1;
    }

    public void setTauditKeyValue1( Long tauditKeyValue1 ) {
        this.tauditKeyValue1 = tauditKeyValue1;
    }
    public Long getTauditKeyValue1() {
        return this.tauditKeyValue1;
    }

    public void setTauditKeyName2( String tauditKeyName2 ) {
        this.tauditKeyName2 = tauditKeyName2;
    }
    public String getTauditKeyName2() {
        return this.tauditKeyName2;
    }

    public void setTauditKeyValue2( Long tauditKeyValue2 ) {
        this.tauditKeyValue2 = tauditKeyValue2;
    }
    public Long getTauditKeyValue2() {
        return this.tauditKeyValue2;
    }

    public void setTauditKeyName3( String tauditKeyName3 ) {
        this.tauditKeyName3 = tauditKeyName3;
    }
    public String getTauditKeyName3() {
        return this.tauditKeyName3;
    }

    public void setTauditKeyValue3( Long tauditKeyValue3 ) {
        this.tauditKeyValue3 = tauditKeyValue3;
    }
    public Long getTauditKeyValue3() {
        return this.tauditKeyValue3;
    }

    public void setTauditKeyName4( String tauditKeyName4 ) {
        this.tauditKeyName4 = tauditKeyName4;
    }
    public String getTauditKeyName4() {
        return this.tauditKeyName4;
    }

    public void setTauditKeyValue4( Long tauditKeyValue4 ) {
        this.tauditKeyValue4 = tauditKeyValue4;
    }
    public Long getTauditKeyValue4() {
        return this.tauditKeyValue4;
    }

    public void setTauditKeyName5( String tauditKeyName5 ) {
        this.tauditKeyName5 = tauditKeyName5;
    }
    public String getTauditKeyName5() {
        return this.tauditKeyName5;
    }

    public void setTauditKeyValue5( Long tauditKeyValue5 ) {
        this.tauditKeyValue5 = tauditKeyValue5;
    }
    public Long getTauditKeyValue5() {
        return this.tauditKeyValue5;
    }

    public void setTauditActionBy( Long tauditActionBy ) {
        this.tauditActionBy = tauditActionBy;
    }
    public Long getTauditActionBy() {
        return this.tauditActionBy;
    }

    public void setTauditActionName( String tauditActionName ) {
        this.tauditActionName = tauditActionName;
    }
    public String getTauditActionName() {
        return this.tauditActionName;
    }

    public void setTauditActionOn( Date tauditActionOn ) {
        this.tauditActionOn = tauditActionOn;
    }
    public Date getTauditActionOn() {
        return this.tauditActionOn;
    }

    public void setTauditActionIp( String tauditActionIp ) {
        this.tauditActionIp = tauditActionIp;
    }
    public String getTauditActionIp() {
        return this.tauditActionIp;
    }

    public void setTauditNotes( String tauditNotes ) {
        this.tauditNotes = tauditNotes;
    }
    public String getTauditNotes() {
        return this.tauditNotes;
    }

    public void setTauditTimeStamp( Date tauditTimeStamp ) {
        this.tauditTimeStamp = tauditTimeStamp;
    }
    public Date getTauditTimeStamp() {
        return this.tauditTimeStamp;
    }

    public void setTauditLockKey( Long tauditLockKey ) {
        this.tauditLockKey = tauditLockKey;
    }
    public Long getTauditLockKey() {
        return this.tauditLockKey;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(tauditKey);
        sb.append("|");
        sb.append(tauditTableName);
        sb.append("|");
        sb.append(tauditRecordType);
        sb.append("|");
        sb.append(tauditKeyName1);
        sb.append("|");
        sb.append(tauditKeyValue1);
        sb.append("|");
        sb.append(tauditKeyName2);
        sb.append("|");
        sb.append(tauditKeyValue2);
        sb.append("|");
        sb.append(tauditKeyName3);
        sb.append("|");
        sb.append(tauditKeyValue3);
        sb.append("|");
        sb.append(tauditKeyName4);
        sb.append("|");
        sb.append(tauditKeyValue4);
        sb.append("|");
        sb.append(tauditKeyName5);
        sb.append("|");
        sb.append(tauditKeyValue5);
        sb.append("|");
        sb.append(tauditActionBy);
        sb.append("|");
        sb.append(tauditActionName);
        sb.append("|");
        sb.append(tauditActionOn);
        sb.append("|");
        sb.append(tauditActionIp);
        sb.append("|");
        sb.append(tauditNotes);
        sb.append("|");
        sb.append(tauditTimeStamp);
        sb.append("|");
        sb.append(tauditLockKey);
        return sb.toString(); 
    } 


}
