

/*
 * Created on 16 Oct 2017 ( Time 10:48:53 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
//import org.hibernate.validator.constraints.* ;
import javax.validation.constraints.Size;


public class TIdVisitRemarksSearch implements Serializable {

    private static final long serialVersionUID = 1L;

    @NotNull
    private Long       pivrKey      ;

    @NotNull 
     private Long       pivrPivKey   ;

    @NotNull
    @Size( min = 1, max = 600 ) 
     private String     pivrVisitNotes ;

    @Size( max = 75 ) 
     private String     activeStatus ;

    @NotNull 
     private Long       lockKey      ;

    @NotNull 
     private Long       profileKey   ;



  
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPivrKey( Long pivrKey ) {
        this.pivrKey = pivrKey ;
    }
    public Long getPivrKey() {
        return this.pivrKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pivr_piv_key ( BIGINT ) 
    public void setPivrPivKey( Long pivrPivKey ) {
        this.pivrPivKey = pivrPivKey;
    }
    public Long getPivrPivKey() {
        return this.pivrPivKey;
    }

    //--- DATABASE MAPPING : pivr_visit_notes ( VARCHAR ) 
    public void setPivrVisitNotes( String pivrVisitNotes ) {
        this.pivrVisitNotes = pivrVisitNotes;
    }
    public String getPivrVisitNotes() {
        return this.pivrVisitNotes;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pivrKey);
        sb.append("]:"); 
        sb.append(pivrPivKey);
        sb.append("|");
        sb.append(pivrVisitNotes);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 

}

