
/*
 * Created on 20 Feb 2017 ( Time 18:45:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
import java.util.Date;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Persistent class for entity stored in table "t_id_business_potential_info"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_business_potential_info")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdBusinessPotentialInfoEntity.countAll", query="SELECT COUNT(x) FROM TIdBusinessPotentialInfoEntity x" )
} )
public class TIdBusinessPotentialInfoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bpi_key", nullable=false)
    private Long       key       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bpi_pin_key", nullable=false)
		
     private Long       bpiPinKey    ;

    @Column(name="bpi_skill_key", nullable=false)
		
     private Long       bpiSkillKey  ;

    @Column(name="bpi_others")
		
     private Long       bpiOthers    ;

    @Column(name="bpi_city_key")
		
     private Long       bpiCityKey   ;

    @Column(name="bpi_remarks", length=2000)
		
     private String     bpiRemarks   ;
    
    @Column(name="bpi_created_by", nullable=false)
    private Long       bpiCreatedBy   ;

    @Column(name="active_status", nullable=false, length=75)
		
     private String     activeStatus ;

    @Column(name="profile_key", nullable=false)
		
     private Long       profileKey   ;

    @Column(name="lock_key", nullable=false)
				@Version
		
     private Long       lockKey      ;

    
    @Column(name="created_on")
    private Date createdOn;

    
    public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdBusinessPotentialInfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKey( Long key ) {
        this.key = key ;
    }
    public Long getKey() {
        return this.key;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bpi_pin_key ( BIGINT ) 
    public void setBpiPinKey( Long bpiPinKey ) {
        this.bpiPinKey = bpiPinKey;
    }
    public Long getBpiPinKey() {
        return this.bpiPinKey;
    }

    //--- DATABASE MAPPING : bpi_skill_key ( BIGINT ) 
    public void setBpiSkillKey( Long bpiSkillKey ) {
        this.bpiSkillKey = bpiSkillKey;
    }
    public Long getBpiSkillKey() {
        return this.bpiSkillKey;
    }

    //--- DATABASE MAPPING : bpi_others ( BIGINT ) 
    public void setBpiOthers( Long bpiOthers ) {
        this.bpiOthers = bpiOthers;
    }
    public Long getBpiOthers() {
        return this.bpiOthers;
    }

    //--- DATABASE MAPPING : bpi_city_key ( BIGINT ) 
    public void setBpiCityKey( Long bpiCityKey ) {
        this.bpiCityKey = bpiCityKey;
    }
    public Long getBpiCityKey() {
        return this.bpiCityKey;
    }

    //--- DATABASE MAPPING : bpi_remarks ( VARCHAR ) 
    public void setBpiRemarks( String bpiRemarks ) {
        this.bpiRemarks = bpiRemarks;
    }
    public String getBpiRemarks() {
        return this.bpiRemarks;
    }
    
    public Long getBpiCreatedBy() {
		return bpiCreatedBy;
	}
	public void setBpiCreatedBy(Long bpiCreatedBy) {
		this.bpiCreatedBy = bpiCreatedBy;
	}

	//--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }
    
    


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    
   

    
  

	
     
	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(key);
        sb.append("]:"); 
        sb.append(bpiPinKey);
        sb.append("|");
        sb.append(bpiSkillKey);
        sb.append("|");
        sb.append(bpiOthers);
        sb.append("|");
        sb.append(bpiCityKey);
        sb.append("|");
        sb.append(bpiRemarks);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(createdOn);
        
        return sb.toString(); 
    } 

}
