
/*
 * Created on 1 Nov 2016 ( Time 10:40:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Persistent class for entity stored in table "t_id_company_contact_link"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_company_contact_link")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdCompanyContactLinkEntity.countAll", query="SELECT COUNT(x) FROM TIdCompanyContactLinkEntity x" )
} )

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIdCompanyContactLinkEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ccl_key", nullable=false)
    private Long       cclKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="ccl_pin_key", nullable=false)
		
     private Long       cclPinKey    ;

    @Column(name="ccl_company_relation", nullable=false, length=1)
		
     private Long     cclCompanyRelation ;

    @Column(name="ccl_company_key", nullable=false)
		
     private Long       cclCompanyKey ;

    @Column(name="active_status", nullable=false, length=75)
		
     private String     activeStatus ;

    @Column(name="lock_key", nullable=false)
				@Version
		
     private Long       lockKey      ;

    @Column(name="profile_key", nullable=false)
		
     private Long       profileKey   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdCompanyContactLinkEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCclKey( Long cclKey ) {
        this.cclKey = cclKey ;
    }
    public Long getCclKey() {
        return this.cclKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ccl_pin_key ( BIGINT ) 
    public void setCclPinKey( Long cclPinKey ) {
        this.cclPinKey = cclPinKey;
    }
    public Long getCclPinKey() {
        return this.cclPinKey;
    }

    //--- DATABASE MAPPING : ccl_company_relation ( VARCHAR ) 
    public void setCclCompanyRelation( Long cclCompanyRelation ) {
        this.cclCompanyRelation = cclCompanyRelation;
    }
    public Long getCclCompanyRelation() {
        return this.cclCompanyRelation;
    }

    //--- DATABASE MAPPING : ccl_company_key ( BIGINT ) 
    public void setCclCompanyKey( Long cclCompanyKey ) {
        this.cclCompanyKey = cclCompanyKey;
    }
    public Long getCclCompanyKey() {
        return this.cclCompanyKey;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(cclKey);
        sb.append("]:"); 
        sb.append(cclPinKey);
        sb.append("|");
        sb.append(cclCompanyRelation);
        sb.append("|");
        sb.append(cclCompanyKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 

}
