/*
 * Created on 20 Nov 2016 ( Time 14:55:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Store;

/**
 * Persistent class for entity stored in table "t_id_country_master"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_country_master")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdCountryMasterEntitySearch.countAll", query="SELECT COUNT(x) FROM TIdCountryMasterEntitySearch x" )
} )
public class TIdCountryMasterEntitySearch implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="country_key", nullable=false)
    private Long       key          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", nullable=false, length=20)
    private String     code         ;

    @Column(name="name", nullable=false, length=240)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     name         ;

    @Column(name="country_abbreviation", length=25)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     countryAbbreviation ;

    @Column(name="country_iso_code", nullable=false, length=25)
    private String     countryIsoCode ;

    @Column(name="country_intl_dial_code", length=25)
    private String     countryIntlDialCode ;

    @Column(name="country_region_key")
    private Long       countryRegionKey ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="active_from")
    private Date       activeFrom   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="active_to")
    private Date       activeTo     ;

    @Column(name="active_status", nullable=false, length=75)
    private String     activeStatus ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;

    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdPersonalInformationEntitySearch.class)
    private List<TIdPersonalInformationEntitySearch> listOfTIdPersonalInformation;

    @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdProfileAddressDetailsEntitySearch.class)
    private List<TIdProfileAddressDetailsEntitySearch> listOfTIdProfileAddressDetails;
    
    @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdExperienceInformationEntitySearch.class)
    private List<TIdExperienceInformationEntitySearch> listOfTIdExperienceInformation;
    
    @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdCityMasterEntitySearch.class)
    private List<TIdCityMasterEntitySearch> listOfTIdCityMaster;
    
   /* @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdEducationalInstitutesEntitySearch.class)
    private List<TIdEducationalInstitutesEntitySearch> listOfTIdEducationalInstitutes;
    
    @OneToMany(mappedBy="tIdCountryMasterSearch", targetEntity=TIdAdditionalInformationEntitySearch.class)
    private List<TIdAdditionalInformationEntitySearch> listOfTIdAdditionalInformation;*/
    
	@OneToMany(mappedBy = "tIdCountryMasterSearch", targetEntity = TIdBusinessPotentialInfoEntitySearch.class)
	private List<TIdBusinessPotentialInfoEntitySearch> listOfTIdBusinessPotentialInfo;

	@OneToMany(mappedBy = "tIdCountryMasterSearch", targetEntity = TIdAddPotentialServicesEntitySearch.class)
	private List<TIdAddPotentialServicesEntitySearch> listOfTIdAddPotentialServices;
    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdCountryMasterEntitySearch() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setKey( Long key ) {
        this.key = key ;
    }
    public Long getKey() {
        return this.key;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : country_abbreviation ( VARCHAR ) 
    public void setCountryAbbreviation( String countryAbbreviation ) {
        this.countryAbbreviation = countryAbbreviation;
    }
    public String getCountryAbbreviation() {
        return this.countryAbbreviation;
    }

    //--- DATABASE MAPPING : country_iso_code ( VARCHAR ) 
    public void setCountryIsoCode( String countryIsoCode ) {
        this.countryIsoCode = countryIsoCode;
    }
    public String getCountryIsoCode() {
        return this.countryIsoCode;
    }

    //--- DATABASE MAPPING : country_intl_dial_code ( VARCHAR ) 
    public void setCountryIntlDialCode( String countryIntlDialCode ) {
        this.countryIntlDialCode = countryIntlDialCode;
    }
    public String getCountryIntlDialCode() {
        return this.countryIntlDialCode;
    }

    //--- DATABASE MAPPING : country_region_key ( BIGINT ) 
    public void setCountryRegionKey( Long countryRegionKey ) {
        this.countryRegionKey = countryRegionKey;
    }
    public Long getCountryRegionKey() {
        return this.countryRegionKey;
    }

    //--- DATABASE MAPPING : active_from ( DATETIME ) 
    public void setActiveFrom( Date activeFrom ) {
        this.activeFrom = activeFrom;
    }
    public Date getActiveFrom() {
        return this.activeFrom;
    }

    //--- DATABASE MAPPING : active_to ( DATETIME ) 
    public void setActiveTo( Date activeTo ) {
        this.activeTo = activeTo;
    }
    public Date getActiveTo() {
        return this.activeTo;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTIdPersonalInformation( List<TIdPersonalInformationEntitySearch> listOfTIdPersonalInformation ) {
        this.listOfTIdPersonalInformation = listOfTIdPersonalInformation;
    }
    public List<TIdPersonalInformationEntitySearch> getListOfTIdPersonalInformation() {
        return this.listOfTIdPersonalInformation;
    }


    public List<TIdProfileAddressDetailsEntitySearch> getListOfTIdProfileAddressDetails() {
		return listOfTIdProfileAddressDetails;
	}

	public void setListOfTIdProfileAddressDetails(
			List<TIdProfileAddressDetailsEntitySearch> listOfTIdProfileAddressDetails) {
		this.listOfTIdProfileAddressDetails = listOfTIdProfileAddressDetails;
	}

	
	public List<TIdExperienceInformationEntitySearch> getListOfTIdExperienceInformation() {
		return listOfTIdExperienceInformation;
	}

	public void setListOfTIdExperienceInformation(
			List<TIdExperienceInformationEntitySearch> listOfTIdExperienceInformation) {
		this.listOfTIdExperienceInformation = listOfTIdExperienceInformation;
	}

	
	public List<TIdCityMasterEntitySearch> getListOfTIdCityMaster() {
		return listOfTIdCityMaster;
	}

	public void setListOfTIdCityMaster(List<TIdCityMasterEntitySearch> listOfTIdCityMaster) {
		this.listOfTIdCityMaster = listOfTIdCityMaster;
	}

	
	/*public List<TIdEducationalInstitutesEntitySearch> getListOfTIdEducationalInstitutes() {
		return listOfTIdEducationalInstitutes;
	}

	public void setListOfTIdEducationalInstitutes(
			List<TIdEducationalInstitutesEntitySearch> listOfTIdEducationalInstitutes) {
		this.listOfTIdEducationalInstitutes = listOfTIdEducationalInstitutes;
	}

	public List<TIdAdditionalInformationEntitySearch> getListOfTIdAdditionalInformation() {
		return listOfTIdAdditionalInformation;
	}

	public void setListOfTIdAdditionalInformation(
			List<TIdAdditionalInformationEntitySearch> listOfTIdAdditionalInformation) {
		this.listOfTIdAdditionalInformation = listOfTIdAdditionalInformation;
	}*/
	public List<TIdBusinessPotentialInfoEntitySearch> getListOfTIdBusinessPotentialInfo() {
		return listOfTIdBusinessPotentialInfo;
	}

	public void setListOfTIdBusinessPotentialInfo(
			List<TIdBusinessPotentialInfoEntitySearch> listOfTIdBusinessPotentialInfo) {
		this.listOfTIdBusinessPotentialInfo = listOfTIdBusinessPotentialInfo;
	}

	public List<TIdAddPotentialServicesEntitySearch> getListOfTIdAddPotentialServices() {
		return listOfTIdAddPotentialServices;
	}

	public void setListOfTIdAddPotentialServices(
			List<TIdAddPotentialServicesEntitySearch> listOfTIdAddPotentialServices) {
		this.listOfTIdAddPotentialServices = listOfTIdAddPotentialServices;
	} 
	
	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(key);
        sb.append("]:"); 
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(countryAbbreviation);
        sb.append("|");
        sb.append(countryIsoCode);
        sb.append("|");
        sb.append(countryIntlDialCode);
        sb.append("|");
        sb.append(countryRegionKey);
        sb.append("|");
        sb.append(activeFrom);
        sb.append("|");
        sb.append(activeTo);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        return sb.toString(); 
    }

	

}
