/*
 * Created on 16 Jan 2018 ( Time 18:35:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "t_id_company_contact_link_view"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_company_contact_link_view")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdCompanyContactLinkViewEntity.countAll", query="SELECT COUNT(x) FROM TIdCompanyContactLinkViewEntity x" )
} )
public class TIdCompanyContactLinkViewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ccl_key", nullable=false)
    private Long       cclKey       ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------
    @Column(name="ccl_pin_key", nullable=false)
    private Long       cclPinKey    ;

    @Column(name="ccl_pin_name", length=100)
    private String     cclPinName   ;

    @Column(name="ccl_company_relation", nullable=false)
    private Long       cclCompanyRelation ;

    @Column(name="ccl_company_relation_value", length=240)
    private String     cclCompanyRelationValue ;

    @Column(name="ccl_company_key", nullable=false)
    private Long       cclCompanyKey ;

    @Column(name="ccl_company_name", length=240)
    private String     cclCompanyName ;

    @Column(name="active_status", nullable=false, length=75)
    private String     activeStatus ;

    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdCompanyContactLinkViewEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ccl_key ( BIGINT ) 
    public void setCclKey( Long cclKey ) {
        this.cclKey = cclKey;
    }
    public Long getCclKey() {
        return this.cclKey;
    }

    //--- DATABASE MAPPING : ccl_pin_key ( BIGINT ) 
    public void setCclPinKey( Long cclPinKey ) {
        this.cclPinKey = cclPinKey;
    }
    public Long getCclPinKey() {
        return this.cclPinKey;
    }

    //--- DATABASE MAPPING : ccl_pin_name ( VARCHAR ) 
    public void setCclPinName( String cclPinName ) {
        this.cclPinName = cclPinName;
    }
    public String getCclPinName() {
        return this.cclPinName;
    }

    //--- DATABASE MAPPING : ccl_company_relation ( BIGINT ) 
    public void setCclCompanyRelation( Long cclCompanyRelation ) {
        this.cclCompanyRelation = cclCompanyRelation;
    }
    public Long getCclCompanyRelation() {
        return this.cclCompanyRelation;
    }

    //--- DATABASE MAPPING : ccl_company_relation_value ( VARCHAR ) 
    public void setCclCompanyRelationValue( String cclCompanyRelationValue ) {
        this.cclCompanyRelationValue = cclCompanyRelationValue;
    }
    public String getCclCompanyRelationValue() {
        return this.cclCompanyRelationValue;
    }

    //--- DATABASE MAPPING : ccl_company_key ( BIGINT ) 
    public void setCclCompanyKey( Long cclCompanyKey ) {
        this.cclCompanyKey = cclCompanyKey;
    }
    public Long getCclCompanyKey() {
        return this.cclCompanyKey;
    }

    //--- DATABASE MAPPING : ccl_company_name ( VARCHAR ) 
    public void setCclCompanyName( String cclCompanyName ) {
        this.cclCompanyName = cclCompanyName;
    }
    public String getCclCompanyName() {
        return this.cclCompanyName;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(cclKey);
        sb.append("|");
        sb.append(cclPinKey);
        sb.append("|");
        sb.append(cclPinName);
        sb.append("|");
        sb.append(cclCompanyRelation);
        sb.append("|");
        sb.append(cclCompanyRelationValue);
        sb.append("|");
        sb.append(cclCompanyKey);
        sb.append("|");
        sb.append(cclCompanyName);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 

}
