/*
 * Created on 13 Dec 2016 ( Time 15:25:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.search.annotations.IndexedEmbedded;

/**
 * Persistent class for entity stored in table "t_id_language_information"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_language_information")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdLanguageInformationEntitySearch.countAll", query="SELECT COUNT(x) FROM TIdLanguageInformationEntitySearch x" )
} )
public class TIdLanguageInformationEntitySearch implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="pli_key", nullable=false)
    private Long       pliKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    /*@Column(name="pli_language_key", nullable=false)
    private Long       pliLanguageKey ;*/

    @Column(name="pli_proficiency", length=1)
    private String     pliProficiency ;

    @Column(name="active_status", nullable=false, length=75)
    private String     activeStatus ;

    @Version
    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;

	// "pliPinKey" (column "pli_pin_key") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="pli_pin_key", referencedColumnName="pin_key")
    private TIdPersonalInformationEntitySearch tIdPersonalInformation;
    
    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pli_language_key", referencedColumnName="language_key")
    private TIdLanguageMasterEntitySearch tIdLanguageMaster;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdLanguageInformationEntitySearch() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPliKey( Long pliKey ) {
        this.pliKey = pliKey ;
    }
    public Long getPliKey() {
        return this.pliKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pli_language_key ( BIGINT ) 
    /*public void setPliLanguageKey( Long pliLanguageKey ) {
        this.pliLanguageKey = pliLanguageKey;
    }
    public Long getPliLanguageKey() {
        return this.pliLanguageKey;
    }*/

    //--- DATABASE MAPPING : pli_proficiency ( VARCHAR ) 
    public void setPliProficiency( String pliProficiency ) {
        this.pliProficiency = pliProficiency;
    }
    public String getPliProficiency() {
        return this.pliProficiency;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTIdPersonalInformation( TIdPersonalInformationEntitySearch tIdPersonalInformation ) {
        this.tIdPersonalInformation = tIdPersonalInformation;
    }
    public TIdPersonalInformationEntitySearch getTIdPersonalInformation() {
        return this.tIdPersonalInformation;
    }
    
    public TIdLanguageMasterEntitySearch getTIdLanguageMaster() {
		return tIdLanguageMaster;
	}
	public void setTIdLanguageMaster(TIdLanguageMasterEntitySearch tIdLanguageMaster) {
		this.tIdLanguageMaster = tIdLanguageMaster;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pliKey);
        sb.append("]:"); 
        sb.append(pliProficiency);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 

}
