/*
 * Created on 6 Mar 2019 ( Time 19:37:22 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.id.wasta.util.action.CommonConstants;

/**
 * Persistent class for entity stored in table "t_id_login_history"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_login_history" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdLoginHistoryEntity.countAll", query="SELECT COUNT(x) FROM TIdLoginHistoryEntity x" )
} )
public class TIdLoginHistoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="lh_key", nullable=false)
     private Long       lhKey        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="lh_user_code", nullable=false)
    private String lhUserCode;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lh_login_time")
    private Date       lhLoginTime ;

    
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lh_logout_time")
    private Date       lhLogoutTime ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdLoginHistoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLhKey( Long lhKey ) {
        this.lhKey = lhKey ;
    }
    public Long getLhKey() {
        return this.lhKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : lh_login_id ( BIGINT ) 
    public String getLhUserCode() {
		return lhUserCode;
	}

	public void setLhUserCode(String lhUserCode) {
		this.lhUserCode = lhUserCode;
	}

    //--- DATABASE MAPPING : lh_login_time ( DATETIME ) 
	public Date getLhLoginTime() {
		return lhLoginTime;
	}

	public void setLhLoginTime(Date lhLoginTime) {
		this.lhLoginTime = lhLoginTime;
	}
	//--- DATABASE MAPPING : lh_logout_time ( DATETIME ) 
	public Date getLhLogoutTime() {
		return lhLogoutTime;
	}

	public void setLhLogoutTime(Date lhLogoutTime) {
		this.lhLogoutTime = lhLogoutTime;
	}
    


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(lhKey);
        sb.append("]:"); 
        sb.append(lhUserCode);
        sb.append("|");
        sb.append(lhLoginTime);
        sb.append("|");
        sb.append(lhLogoutTime);
        return sb.toString(); 
    }

}
