/*
 * Created on 31 Aug 2017 ( Time 17:50:30 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Persistent class for entity stored in table "t_id_my_contacts_link"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity    
@Table(name = "t_id_my_contacts_link") 
// Define named queries here
@NamedQueries({ @NamedQuery(name = "TIdMyContactsLinkEntity.countAll", query = "SELECT COUNT(x) FROM TIdMyContactsLinkEntity x") })
public class TIdMyContactsLinkEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "mcl_key", nullable = false)
	private Long key;

	@Column(name = "mcl_from_pin_key", nullable = false)
	private Long mclFromPinKey;

	@Column(name = "mcl_to_pin_key", nullable = false)
	private Long mclToPinKey;
	
	@Column(name = "mcl_star_rating", nullable = false)
	private Long mclStarRating;

	@Column(name = "active_status", nullable = false, length = 225)
	private String activeStatus;

	@Version
	@Column(name = "lock_key", nullable = false)
	private Long lockKey;

	@Column(name = "profile_key", nullable = false)
	private Long profileKey;

	public TIdMyContactsLinkEntity() {
		super();
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public Long getMclFromPinKey() {
		return mclFromPinKey;
	}

	public void setMclFromPinKey(Long mclFromPinKey) {
		this.mclFromPinKey = mclFromPinKey;
	}

	public Long getMclToPinKey() {
		return mclToPinKey;
	}

	public void setMclToPinKey(Long mclToPinKey) {
		this.mclToPinKey = mclToPinKey;
	}

	public Long getMclStarRating() {
		return mclStarRating;
	}

	public void setMclStarRating(Long mclStarRating) {
		this.mclStarRating = mclStarRating;
	}

	public String getActiveStatus() {
		return activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	public Long getLockKey() {
		return lockKey;
	}

	public void setLockKey(Long lockKey) {
		this.lockKey = lockKey;
	}

	public Long getProfileKey() {
		return profileKey;
	}

	public void setProfileKey(Long profileKey) {
		this.profileKey = profileKey;
	}
	
}
