/*
 * Created on 17 Nov 2016 ( Time 19:54:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.Store;

/**
 * Persistent class for entity stored in table "t_id_personal_information"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Indexed
@Table(name="t_id_personal_information")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdPersonalInformationEntitySearch.countAll", query="SELECT COUNT(x) FROM TIdPersonalInformationEntitySearch x" )
} )
public class TIdPersonalInformationEntitySearch implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="pin_key", nullable=false)
    private Long       pinKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
  /*  @Column(name="pin_title", nullable=false, length=125)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinTitle     ;*/

    @Column(name="pin_first_name", nullable=false, length=100)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinFirstName ;

    @Column(name="pin_last_name", length=100)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinLastName  ;

    @Column(name="pin_nick_name", length=100)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinNickName  ;

    @Column(name="pin_gender", nullable=false, length=125)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinGender    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pin_dob")
    private Date       pinDob       ;
    
    @Column(name="pin_parent_key")
    private Long pinParentKey;
    
    @Column(name="pin_dob_str")
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String pinDobStr;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pin_doa")
	private Date       pinDoa       ;

    @Column(name="pin_email", length=75)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinEmail     ;

    @Column(name="pin_address", length=500)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinAddress   ;

    @Column(name="pin_remarks", length=1000)
    @Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
    private String     pinRemarks   ;
    
    @Column(name="pin_creator_key")
    private Long pinCreatorKey;

    @Column(name="pin_previous_status", nullable=false, length=75)
    private String     pinPreviousStatus ;
    
    @Column(name="active_status", nullable=false, length=75)
    private String     activeStatus ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;

    @Version
    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;
    
    @Transient
    private Set<String> category	;
    
    @Transient
    private Long yearOfBirth;
    
    @Transient
    private Long age;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date modifiedOn; 
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	@IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdEducationalInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdEducationalInformationEntitySearch> listOfTIdEducationalInformation;

    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdExperienceInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdExperienceInformationEntitySearch> listOfTIdExperienceInformation;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdVisitInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdVisitInformationEntitySearch> listOfTIdVisitInformation;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdRelationshipInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdRelationshipInformationEntitySearch> listOfTIdRelationshipInformation;

    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pin_city_key", referencedColumnName="city_key")
    private TIdCityMasterEntitySearch tIdCityMasterSearch;
    
    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pin_country_key", referencedColumnName="country_key")
    private TIdCountryMasterEntitySearch tIdCountryMasterSearch;
    
    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pin_state_key", referencedColumnName="state_key")
    private TIdStateMasterEntitySearch tIdStateMasterSearch;
    
    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pin_nationality_key", referencedColumnName="nationality_key")
    private TIdNationalityMasterEntitySearch tIdNationalityMasterSearch;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdAwardsInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdAwardsInformationEntitySearch> listOfTIdAwardsInformation;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdProjectsInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdProjectsInformationEntitySearch> listOfTIdProjectsInformation;  
    
    @IndexedEmbedded
	@OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdMiscInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdMiscInformationEntitySearch> listOfTIdMiscInformation;
    
    @IndexedEmbedded
	@OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdAdditionalInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdAdditionalInformationEntitySearch> listOfTIdAdditionalInformation;

    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdLanguageInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdLanguageInformationEntitySearch> listOfTIdLanguageInformation;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdRelationshipInfoLinkEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdRelationshipInfoLinkEntitySearch> listOfTIdRelationshipInfoLink;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdCompanyContactLinkEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdCompanyContactLinkEntitySearch> listOfTIdCompanyContactLink;
   
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdPersonalInfoLinkEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdPersonalInfoLinkEntitySearch> listOfTIdPersonalInfoLink;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdProfessionalExpertiseEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdProfessionalExpertiseEntitySearch> listOfTIdProfessionalExpertise;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdProfessionalInterestsEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdProfessionalInterestsEntitySearch> listOfTIdProfessionalInterests;

    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdPersonalInterestsEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdPersonalInterestsEntitySearch> listOfTIdPersonalInterests;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdBusinessPotentialInfoEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdBusinessPotentialInfoEntitySearch> listOfTIdBusinessPotentialInfo;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdAddPotentialServicesEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdAddPotentialServicesEntitySearch> listOfTIdAddPotentialServices;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdPersonalPrioritiesEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdPersonalPrioritiesEntitySearch> listOfTIdPersonalPriorities;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdRecreationInfoEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdRecreationInfoEntitySearch> listOfTIdRecreationInfo;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdProfileAddressDetailsEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdProfileAddressDetailsEntitySearch> listOfTIdProfileAddressDetails;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdCommunicationInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdCommunicationInformationEntitySearch> listOfTIdCommunicationInformation;
    
    @IndexedEmbedded
    @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdSocialMediaInformationEntitySearch.class, cascade = CascadeType.ALL)
    private List<TIdSocialMediaInformationEntitySearch> listOfTIdSocialMediaInformation;
    
    @IndexedEmbedded
    @ManyToOne
    @JoinColumn(name="pin_title", referencedColumnName="rcd_detail_key")
    private TIdReferenceCodesDetailEntity tIdReferenceCodesDetail;
    
	//----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdPersonalInformationEntitySearch() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPinKey( Long pinKey ) {
        this.pinKey = pinKey ;
    }
    public Long getPinKey() {
        return this.pinKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pin_title ( VARCHAR ) 
   /* public void setPinTitle( String pinTitle ) {
        this.pinTitle = pinTitle;
    }
    public String getPinTitle() {
        return this.pinTitle;
    }*/

    //--- DATABASE MAPPING : pin_first_name ( VARCHAR ) 
    public void setPinFirstName( String pinFirstName ) {
        this.pinFirstName = pinFirstName;
    }
    public String getPinFirstName() {
        return this.pinFirstName;
    }

    //--- DATABASE MAPPING : pin_last_name ( VARCHAR ) 
    public void setPinLastName( String pinLastName ) {
        this.pinLastName = pinLastName;
    }
    public String getPinLastName() {
        return this.pinLastName;
    }

    //--- DATABASE MAPPING : pin_nick_name ( VARCHAR ) 
    public void setPinNickName( String pinNickName ) {
        this.pinNickName = pinNickName;
    }
    public String getPinNickName() {
        return this.pinNickName;
    }

    //--- DATABASE MAPPING : pin_gender ( VARCHAR ) 
    public void setPinGender( String pinGender ) {
        this.pinGender = pinGender;
    }
    public String getPinGender() {
        return this.pinGender;
    }
    
    

    public List<TIdPersonalInfoLinkEntitySearch> getListOfTIdPersonalInfoLink() {
		return listOfTIdPersonalInfoLink;
	}

	public void setListOfTIdPersonalInfoLink(
			List<TIdPersonalInfoLinkEntitySearch> listOfTIdPersonalInfoLink) {
		this.listOfTIdPersonalInfoLink = listOfTIdPersonalInfoLink;
	}

	//--- DATABASE MAPPING : pin_dob ( DATETIME ) 
    public void setPinDob( Date pinDob ) {
        this.pinDob = pinDob;
    }
    public Date getPinDob() {
        return this.pinDob;
    }

    //--- DATABASE MAPPING : pin_email ( VARCHAR ) 
    public void setPinEmail( String pinEmail ) {
        this.pinEmail = pinEmail;
    }
    public String getPinEmail() {
        return this.pinEmail;
    }

    //--- DATABASE MAPPING : pin_address ( VARCHAR ) 
    public void setPinAddress( String pinAddress ) {
        this.pinAddress = pinAddress;
    }
    public String getPinAddress() {
        return this.pinAddress;
    }
    
    public Long getPinParentKey() {
		return pinParentKey;
	}

	public void setPinParentKey(Long pinParentKey) {
		this.pinParentKey = pinParentKey;
	}

	//--- DATABASE MAPPING : pin_remarks ( VARCHAR ) 
    public void setPinRemarks( String pinRemarks ) {
        this.pinRemarks = pinRemarks;
    }
    public String getPinRemarks() {
        return this.pinRemarks;
    }

    public Long getPinCreatorKey() {
		return pinCreatorKey;
	}
	public void setPinCreatorKey(Long pinCreatorKey) {
		this.pinCreatorKey = pinCreatorKey;
	}

	public String getPinPreviousStatus() {
		return pinPreviousStatus;
	}
	public void setPinPreviousStatus(String pinPreviousStatus) {
		this.pinPreviousStatus = pinPreviousStatus;
	}

	//--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }
    
    public Set<String> getCategory() {
		return category;
	}
	public void setCategory(Set<String> category) {
		this.category = category;
	}

    public String getPinDobStr() {
		return pinDobStr;
	}

	public void setPinDobStr(String pinDobStr) {
		this.pinDobStr = pinDobStr;
	}
	
	public Date getPinDoa() {
		return pinDoa;
	}
	
	public void setPinDoa(Date pinDoa) {
		this.pinDoa = pinDoa;
	}
	
	public Long getYearOfBirth() {
		return yearOfBirth;
	}

	public void setYearOfBirth(Long yearOfBirth) {
		this.yearOfBirth = yearOfBirth;
	}

	public Long getAge() {
		return age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
	public List<TIdAdditionalInformationEntitySearch> getListOfTIdAdditionalInformation() {
		return listOfTIdAdditionalInformation;
	}

	public void setListOfTIdAdditionalInformation(
			List<TIdAdditionalInformationEntitySearch> listOfTIdAdditionalInformation) {
		this.listOfTIdAdditionalInformation = listOfTIdAdditionalInformation;
	}
    
    public List<TIdMiscInformationEntitySearch> getListOfTIdMiscInformation() {
		return listOfTIdMiscInformation;
	}

	public void setListOfTIdMiscInformation(List<TIdMiscInformationEntitySearch> listOfTIdMiscInformation) {
		this.listOfTIdMiscInformation = listOfTIdMiscInformation;
	}
    
    public List<TIdProjectsInformationEntitySearch> getListOfTIdProjectsInformation() {
		return listOfTIdProjectsInformation;
	}

	public void setListOfTIdProjectsInformation(List<TIdProjectsInformationEntitySearch> listOfTIdProjectsInformation) {
		this.listOfTIdProjectsInformation = listOfTIdProjectsInformation;
	}
    
    public void setListOfTIdEducationalInformation( List<TIdEducationalInformationEntitySearch> listOfTIdEducationalInformation ) {
        this.listOfTIdEducationalInformation = listOfTIdEducationalInformation;
    }
    public List<TIdEducationalInformationEntitySearch> getListOfTIdEducationalInformation() {
        return this.listOfTIdEducationalInformation;
    }

    public void setListOfTIdExperienceInformation( List<TIdExperienceInformationEntitySearch> listOfTIdExperienceInformation ) {
        this.listOfTIdExperienceInformation = listOfTIdExperienceInformation;
    }
    public List<TIdExperienceInformationEntitySearch> getListOfTIdExperienceInformation() {
        return this.listOfTIdExperienceInformation;
    }

	public List<TIdVisitInformationEntitySearch> getListOfTIdVisitInformation() {
		return listOfTIdVisitInformation;
	}

	public void setListOfTIdVisitInformation(List<TIdVisitInformationEntitySearch> listOfTIdVisitInformation) {
		this.listOfTIdVisitInformation = listOfTIdVisitInformation;
	}

	
	public List<TIdRelationshipInformationEntitySearch> getListOfTIdRelationshipInformation() {
		return listOfTIdRelationshipInformation;
	}

	public void setListOfTIdRelationshipInformation(
			List<TIdRelationshipInformationEntitySearch> listOfTIdRelationshipInformation) {
		this.listOfTIdRelationshipInformation = listOfTIdRelationshipInformation;
	}

	public TIdCityMasterEntitySearch gettIdCityMasterSearch() {
		return tIdCityMasterSearch;
	}

	public void settIdCityMasterSearch(TIdCityMasterEntitySearch tIdCityMasterSearch) {
		this.tIdCityMasterSearch = tIdCityMasterSearch;
	}

	public TIdCountryMasterEntitySearch gettIdCountryMasterSearch() {
		return tIdCountryMasterSearch;
	}

	public void settIdCountryMasterSearch(
			TIdCountryMasterEntitySearch tIdCountryMasterSearch) {
		this.tIdCountryMasterSearch = tIdCountryMasterSearch;
	}

	public TIdStateMasterEntitySearch gettIdStateMasterSearch() {
		return tIdStateMasterSearch;
	}

	public void settIdStateMasterSearch(
			TIdStateMasterEntitySearch tIdStateMasterSearch) {
		this.tIdStateMasterSearch = tIdStateMasterSearch;
	}

	public TIdNationalityMasterEntitySearch gettIdNationalityMasterSearch() {
		return tIdNationalityMasterSearch;
	}

	public void settIdNationalityMasterSearch(
			TIdNationalityMasterEntitySearch tIdNationalityMasterSearch) {
		this.tIdNationalityMasterSearch = tIdNationalityMasterSearch;
	}

	public List<TIdAwardsInformationEntitySearch> getListOfTIdAwardsInformation() {
		return listOfTIdAwardsInformation;
	}

	public void setListOfTIdAwardsInformation(List<TIdAwardsInformationEntitySearch> listOfTIdAwardsInformation) {
		this.listOfTIdAwardsInformation = listOfTIdAwardsInformation;
	}
	
	public void setListOfTIdLanguageInformation( List<TIdLanguageInformationEntitySearch> listOfTIdLanguageInformation ) {
        this.listOfTIdLanguageInformation = listOfTIdLanguageInformation;
    }
	
    public List<TIdLanguageInformationEntitySearch> getListOfTIdLanguageInformation() {
        return this.listOfTIdLanguageInformation;
    }
    
	public List<TIdRelationshipInfoLinkEntitySearch> getListOfTIdRelationshipInfoLink() {
		return listOfTIdRelationshipInfoLink;
	}

	public void setListOfTIdRelationshipInfoLink(List<TIdRelationshipInfoLinkEntitySearch> listOfTIdRelationshipInfoLink) {
		this.listOfTIdRelationshipInfoLink = listOfTIdRelationshipInfoLink;
	}
	
	
	public List<TIdCompanyContactLinkEntitySearch> getListOfTIdCompanyContactLink() {
		return listOfTIdCompanyContactLink;
	}

	public void setListOfTIdCompanyContactLink(
			List<TIdCompanyContactLinkEntitySearch> listOfTIdCompanyContactLink) {
		this.listOfTIdCompanyContactLink = listOfTIdCompanyContactLink;
	}
	public List<TIdProfessionalExpertiseEntitySearch> getListOfTIdProfessionalExpertise() {
		return listOfTIdProfessionalExpertise;
	}

	public void setListOfTIdProfessionalExpertise(
			List<TIdProfessionalExpertiseEntitySearch> listOfTIdProfessionalExpertise) {
		this.listOfTIdProfessionalExpertise = listOfTIdProfessionalExpertise;
	}
	public List<TIdProfessionalInterestsEntitySearch> getListOfTIdProfessionalInterests() {
		return listOfTIdProfessionalInterests;
	}

	public void setListOfTIdProfessionalInterests(
			List<TIdProfessionalInterestsEntitySearch> listOfTIdProfessionalInterests) {
		this.listOfTIdProfessionalInterests = listOfTIdProfessionalInterests;
	}
	
	public List<TIdPersonalInterestsEntitySearch> getListOfTIdPersonalInterests() {
		return listOfTIdPersonalInterests;
	}

	public void setListOfTIdPersonalInterests(List<TIdPersonalInterestsEntitySearch> listOfTIdPersonalInterests) {
		this.listOfTIdPersonalInterests = listOfTIdPersonalInterests;
	}

	public List<TIdBusinessPotentialInfoEntitySearch> getListOfTIdBusinessPotentialInfo() {
		return listOfTIdBusinessPotentialInfo;
	}

	public void setListOfTIdBusinessPotentialInfo(
			List<TIdBusinessPotentialInfoEntitySearch> listOfTIdBusinessPotentialInfo) {
		this.listOfTIdBusinessPotentialInfo = listOfTIdBusinessPotentialInfo;
	}
	
	public List<TIdAddPotentialServicesEntitySearch> getListOfTIdAddPotentialServices() {
		return listOfTIdAddPotentialServices;
	}

	public void setListOfTIdAddPotentialServices(List<TIdAddPotentialServicesEntitySearch> listOfTIdAddPotentialServices) {
		this.listOfTIdAddPotentialServices = listOfTIdAddPotentialServices;
	}
	public List<TIdPersonalPrioritiesEntitySearch> getListOfTIdPersonalPriorities() {
		return listOfTIdPersonalPriorities;
	}

	public void setListOfTIdPersonalPriorities(List<TIdPersonalPrioritiesEntitySearch> listOfTIdPersonalPriorities) {
		this.listOfTIdPersonalPriorities = listOfTIdPersonalPriorities;
	}
	public List<TIdRecreationInfoEntitySearch> getListOfTIdRecreationInfo() {
		return listOfTIdRecreationInfo;
	}

	public void setListOfTIdRecreationInfo(List<TIdRecreationInfoEntitySearch> listOfTIdRecreationInfo) {
		this.listOfTIdRecreationInfo = listOfTIdRecreationInfo;
	}
	
	public List<TIdProfileAddressDetailsEntitySearch> getListOfTIdProfileAddressDetails() {
		return listOfTIdProfileAddressDetails;
	}

	public void setListOfTIdProfileAddressDetails(
			List<TIdProfileAddressDetailsEntitySearch> listOfTIdProfileAddressDetails) {
		this.listOfTIdProfileAddressDetails = listOfTIdProfileAddressDetails;
	}

	public TIdReferenceCodesDetailEntity gettIdReferenceCodesDetail() {
		return tIdReferenceCodesDetail;
	}

	public void settIdReferenceCodesDetail(TIdReferenceCodesDetailEntity tIdReferenceCodesDetail) {
		this.tIdReferenceCodesDetail = tIdReferenceCodesDetail;
	}
	
	public List<TIdCommunicationInformationEntitySearch> getListOfTIdCommunicationInformation() {
		return listOfTIdCommunicationInformation;
	}
	
	public void setListOfTIdCommunicationInformation(
			List<TIdCommunicationInformationEntitySearch> listOfTIdCommunicationInformation) {
		this.listOfTIdCommunicationInformation = listOfTIdCommunicationInformation;
	}
	
	public List<TIdSocialMediaInformationEntitySearch> getListOfTIdSocialMediaInformation() {
		return listOfTIdSocialMediaInformation;
	}

	public void setListOfTIdSocialMediaInformation(
			List<TIdSocialMediaInformationEntitySearch> listOfTIdSocialMediaInformation) {
		this.listOfTIdSocialMediaInformation = listOfTIdSocialMediaInformation;
	}
	
	public Date getModifiedOn() {
		return modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pinKey);
        sb.append("]:"); 
        /*sb.append(pinTitle);
        sb.append("|");*/
        sb.append(pinFirstName);
        sb.append("|");
        sb.append(pinLastName);
        sb.append("|");
        sb.append(pinNickName);
        sb.append("|");
        sb.append(pinGender);
        sb.append("|");
        sb.append(pinDob);
        sb.append("|");
        sb.append(pinEmail);
        sb.append("|");
        sb.append(pinAddress);
        sb.append("|");
        sb.append(pinRemarks);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(pinDobStr);
        return sb.toString(); 
    } 

}
