/*
 * Created on 11 Nov 2016 ( Time 18:58:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.id.wasta.util.action.CommonConstants;

/**
 * Persistent class for entity stored in table "t_id_profile_view_details_view"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_profile_view_details_view")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdProfileViewDetailsViewEntity.countAll", query="SELECT COUNT(x) FROM TIdProfileViewDetailsViewEntity x" )
} )
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIdProfileViewDetailsViewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------
    @Id
    @Column(name="pvd_key", nullable=false)
    private Long       pvdKey       ;

    @Column(name="pvd_pin_key", nullable=false)
    private Long       pvdPinKey    ;

    @Column(name="pvd_pin_viewedby_key", nullable=false)
    private Long       pvdPinViewedbyKey ;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="pvd_viewed_date", nullable=false)
    private Date       pvdViewedDate ;

    @Column(name="active_status", nullable=false, length=75)
    private String     activeStatus ;

    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;

    @Column(name="viewedby_first_name", nullable=false, length=75)
    private String     viewedbyFirstName ;
    
    @Column(name="viewedby_last_name", nullable=false, length=75)
    private String     viewedbyLastName ;

    @Column(name="company_name", nullable=false, length=75)
    private String     companyName ;
    
    @Column(name="designation", nullable=false, length=75)
    private String     designation ;
    
    @Column(name="role", nullable=false, length=75)
    private String     role ;

    @Column(name="functional_area", nullable=false, length=75)
    private String     functionalArea ;
    
    @Column(name="patt_internal_file_name")
    private String     pattInternalFileName ;
    
    @Column(name="patt_reference_key")
    private Long       pattReferenceKey   ;
    
    @Column(name="pex_pin_key")
    private Long       viewedByPinKey   ;
    
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdProfileViewDetailsViewEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pvd_key ( BIGINT ) 
    public void setPvdKey( Long pvdKey ) {
        this.pvdKey = pvdKey;
    }
    public Long getPvdKey() {
        return this.pvdKey;
    }

    //--- DATABASE MAPPING : pvd_pin_key ( BIGINT ) 
    public void setPvdPinKey( Long pvdPinKey ) {
        this.pvdPinKey = pvdPinKey;
    }
    public Long getPvdPinKey() {
        return this.pvdPinKey;
    }

    //--- DATABASE MAPPING : pvd_pin_viewedby_key ( BIGINT ) 
    public void setPvdPinViewedbyKey( Long pvdPinViewedbyKey ) {
        this.pvdPinViewedbyKey = pvdPinViewedbyKey;
    }
    public Long getPvdPinViewedbyKey() {
        return this.pvdPinViewedbyKey;
    }

    //--- DATABASE MAPPING : pvd_viewed_date ( DATETIME ) 
    public void setPvdViewedDate( Date pvdViewedDate ) {
        this.pvdViewedDate = pvdViewedDate;
    }
    public Date getPvdViewedDate() {
        return this.pvdViewedDate;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }
//-----DATABASE MAPPING :viewedby_first_name(VARCHAR)
    public String getViewedbyFirstName() {
		return viewedbyFirstName;
	}

	public void setViewedbyFirstName(String viewedbyFirstName) {
		this.viewedbyFirstName = viewedbyFirstName;
	}
//--DATABASE MAPPING :viewedby_last_name(VARCHAR)
	public String getViewedbyLastName() {
		return viewedbyLastName;
	}

	public void setViewedbyLastName(String viewedbyLastName) {
		this.viewedbyLastName = viewedbyLastName;
	}
//----DATABASE MAPPING :company_name(VARCHAR)
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
//DATABASE MAPPING : designation (VARCHAR)
	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	//DATABASE MAPPING : role (VARCHAR)
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}

	//DATABASE MAPPING : functional_area (VARCHAR)
	public String getFunctionalArea() {
		return functionalArea;
	}
	public void setFunctionalArea(String functionalArea) {
		this.functionalArea = functionalArea;
	}
	
	public String getPattInternalFileName() {
		return pattInternalFileName;
	}
	public void setPattInternalFileName(String pattInternalFileName) {
		this.pattInternalFileName = pattInternalFileName;
	}

	public Long getPattReferenceKey() {
		return pattReferenceKey;
	}
	public void setPattReferenceKey(Long pattReferenceKey) {
		this.pattReferenceKey = pattReferenceKey;
	}

	public Long getViewedByPinKey() {
		return viewedByPinKey;
	}
	public void setViewedByPinKey(Long viewedByPinKey) {
		this.viewedByPinKey = viewedByPinKey;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(pvdKey);
        sb.append("|");
        sb.append(pvdPinKey);
        sb.append("|");
        sb.append(pvdPinViewedbyKey);
        sb.append("|");
        sb.append(pvdViewedDate);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(viewedbyFirstName);
        sb.append("|");
        sb.append(viewedbyLastName);
        sb.append("|");
        sb.append(designation);
        sb.append("|");
        sb.append(role);
        sb.append("|");
        sb.append(functionalArea);
        return sb.toString(); 
    } 

}
