
/*
 * Created on 28 Aug 2017 ( Time 18:04:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

import com.id.util.data.repository.jpa.validators.constraints.CompositeUnique;

/**
 * Persistent class for entity stored in table "t_id_prog_access_blocks"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_prog_access_blocks")
// Define named queries here
@CompositeUnique(columnNames={"pabPahKey", "pabPabmKey"}, message="pabPahKey and pabPabmKey already exist")
@NamedQueries ( {
  @NamedQuery ( name="TIdProgAccessBlocksEntity.countAll", query="SELECT COUNT(x) FROM TIdProgAccessBlocksEntity x" )
} )
public class TIdProgAccessBlocksEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="pab_key", nullable=false)
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long       pabKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="pab_pah_key", nullable=false)
		
     private Long       pabPahKey    ;

    @Column(name="pab_pabm_key", nullable=false)
		
     private Long       pabPabmKey   ;

    @Column(name="active_status", nullable=false, length=225)
		
     private String     activeStatus ;

    @Column(name="lock_key", nullable=false)
				@Version
		
     private Long       lockKey      ;

    @Column(name="profile_key", nullable=false)
		
     private Long       profileKey   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdProgAccessBlocksEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPabKey( Long pabKey ) {
        this.pabKey = pabKey ;
    }
    public Long getPabKey() {
        return this.pabKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pab_pah_key ( BIGINT ) 
    public void setPabPahKey( Long pabPahKey ) {
        this.pabPahKey = pabPahKey;
    }
    public Long getPabPahKey() {
        return this.pabPahKey;
    }

    //--- DATABASE MAPPING : pab_pabm_key ( BIGINT ) 
    public void setPabPabmKey( Long pabPabmKey ) {
        this.pabPabmKey = pabPabmKey;
    }
    public Long getPabPabmKey() {
        return this.pabPabmKey;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pabKey);
        sb.append("]:"); 
        sb.append(pabPahKey);
        sb.append("|");
        sb.append(pabPabmKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(profileKey);
        return sb.toString(); 
    } 

}
