/*
 * Created on 28 Aug 2017 ( Time 18:06:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "t_id_prog_access_fields_master"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "t_id_prog_access_fields_master")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "TIdProgAccessFieldsMasterEntity.countAll", query = "SELECT COUNT(x) FROM TIdProgAccessFieldsMasterEntity x") })
public class TIdProgAccessFieldsMasterEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Id
	@Column(name = "pafm_key", nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long key;

	@Column(name = "pafm_pabm_key", nullable = false)
	private Long pafmPabmKey;

	@Column(name = "pafm_field_name", nullable = false, length = 300)
	private String name;

	@Column(name = "pafm_column_id", nullable = false, length = 90)
	private String code;

	@Column(name = "active_status", nullable = false, length = 225)
	private String activeStatus;

	@Column(name = "lock_key", nullable = false)
	@Version
	private Long lockKey;

	@Column(name = "profile_key", nullable = false)
	private Long profileKey;
	


	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public TIdProgAccessFieldsMasterEntity() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : pafm_key ( BIGINT )

	// --- DATABASE MAPPING : pafm_pabm_key ( BIGINT )
	public void setPafmPabmKey(Long pafmPabmKey) {
		this.pafmPabmKey = pafmPabmKey;
	}

	public Long getPafmPabmKey() {
		return this.pafmPabmKey;
	}

	// --- DATABASE MAPPING : pafm_field_name ( VARCHAR )

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// --- DATABASE MAPPING : pafm_column_id ( VARCHAR )

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	// --- DATABASE MAPPING : active_status ( VARCHAR )
	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	public String getActiveStatus() {
		return this.activeStatus;
	}

	// --- DATABASE MAPPING : lock_key ( BIGINT )
	public void setLockKey(Long lockKey) {
		this.lockKey = lockKey;
	}

	public Long getLockKey() {
		return this.lockKey;
	}

	// --- DATABASE MAPPING : profile_key ( BIGINT )
	public void setProfileKey(Long profileKey) {
		this.profileKey = profileKey;
	}

	public Long getProfileKey() {
		return this.profileKey;
	}
	

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append("]:");
		sb.append(key);
		sb.append("|");
		sb.append(pafmPabmKey);
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(code);
		sb.append("|");
		sb.append(activeStatus);
		sb.append("|");
		sb.append(lockKey);
		sb.append("|");
		sb.append(profileKey);
		return sb.toString();
	}

}
