
/*
 * Created on 4 Nov 2016 ( Time 12:24:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.id.wasta.util.action.CommonConstants;

/**
 * Persistent class for entity stored in table "t_id_personal_information"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_personal_information")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdPersonalInformationEntity.countAll", query="SELECT COUNT(x) FROM TIdPersonalInformationEntity x" )
} )
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIdPersonalInformationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="pin_key", nullable=false)
    private Long       pinKey       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="pin_title", nullable=false)
		
     private Long     pinTitle     ;

    @Column(name="pin_first_name", nullable=false, length=75)
		
     private String     pinFirstName ;

    @Column(name="pin_last_name", length=75)
		
     private String     pinLastName  ;

    @Column(name="pin_nick_name", length=75)
		
     private String     pinNickName  ;

    @Column(name="pin_gender", nullable=false, length=1)
		
     private String     pinGender    ;

    @Column(name="pin_nationality_key")
		
     private Long       pinNationalityKey ;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name="pin_dob")
	private Date       pinDob       ;
    
    @Column(name="pin_dob_str")
    private String      pinDobStr	;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name="pin_doa")
	private Date       pinDoa       ;
    
    @Column(name="pin_email", length=75)
		
     private String     pinEmail     ;

    @Column(name="pin_address", length=500)
		
     private String     pinAddress   ;

    @Column(name="pin_city_key")
		
     private Long       pinCityKey   ;

    @Column(name="pin_state_key")
		
     private Long       pinStateKey  ;

    @Column(name="pin_country_key")
		
     private Long       pinCountryKey ;

    @Column(name="pin_remarks", length=1000)
		
     private String     pinRemarks   ;
    
    @Column(name="pin_creator_key")
    private Long pinCreatorKey;

    @Column(name="pin_previous_status", nullable=false, length=75)
    private String     pinPreviousStatus ;
    
    @Column(name="active_status", nullable=false, length=75)
     private String     activeStatus ;

    @Column(name="profile_key", nullable=false)
     private Long       profileKey   ;

    @Column(name="lock_key", nullable=false)
	@Version
    private Long       lockKey      ;
  
    @Column(name="pin_parent_key", nullable=false)
    private Long pinParentKey;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date modifiedOn;
    
    @Column(name="pin_percentage")
    private Long pinPercentage;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
  /*  @OneToMany(mappedBy="tIdPersonalInformation", targetEntity=TIdCommunicationInformationEntity.class, cascade=CascadeType.ALL)
    private List<TIdCommunicationInformationEntity> listOfTIdCommunicationInformation;   */


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdPersonalInformationEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPinKey( Long pinKey ) {
        this.pinKey = pinKey ;
    }
    public Long getPinKey() {
        return this.pinKey;
    }

    public Long getPinParentKey() {
		return pinParentKey;
	}

	public void setPinParentKey(Long pinParentKey) {
		this.pinParentKey = pinParentKey;
	}

	//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pin_title ( VARCHAR ) 
    public void setPinTitle( Long pinTitle ) {
        this.pinTitle = pinTitle;
    }
    public Long getPinTitle() {
        return this.pinTitle;
    }

    //--- DATABASE MAPPING : pin_first_name ( VARCHAR ) 
    public void setPinFirstName( String pinFirstName ) {
        this.pinFirstName = pinFirstName;
    }
    public String getPinFirstName() {
        return this.pinFirstName;
    }

    //--- DATABASE MAPPING : pin_last_name ( VARCHAR ) 
    public void setPinLastName( String pinLastName ) {
        this.pinLastName = pinLastName;
    }
    public String getPinLastName() {
        return this.pinLastName;
    }

    //--- DATABASE MAPPING : pin_nick_name ( VARCHAR ) 
    public void setPinNickName( String pinNickName ) {
        this.pinNickName = pinNickName;
    }
    public String getPinNickName() {
        return this.pinNickName;
    }

    //--- DATABASE MAPPING : pin_gender ( VARCHAR ) 
    public void setPinGender( String pinGender ) {
        this.pinGender = pinGender;
    }
    public String getPinGender() {
        return this.pinGender;
    }

    //--- DATABASE MAPPING : pin_nationality_key ( BIGINT ) 
    public void setPinNationalityKey( Long pinNationalityKey ) {
        this.pinNationalityKey = pinNationalityKey;
    }
    public Long getPinNationalityKey() {
        return this.pinNationalityKey;
    }

    //--- DATABASE MAPPING : pin_dob ( DATETIME ) 
    public void setPinDob( Date pinDob ) {
        this.pinDob = pinDob;
    }
    public Date getPinDob() {
        return this.pinDob;
    }

    //--- DATABASE MAPPING : pin_email ( VARCHAR ) 
    public void setPinEmail( String pinEmail ) {
        this.pinEmail = pinEmail;
    }
    public String getPinEmail() {
        return this.pinEmail;
    }

    //--- DATABASE MAPPING : pin_address ( VARCHAR ) 
    public void setPinAddress( String pinAddress ) {
        this.pinAddress = pinAddress;
    }
    public String getPinAddress() {
        return this.pinAddress;
    }

    //--- DATABASE MAPPING : pin_city_key ( BIGINT ) 
    public void setPinCityKey( Long pinCityKey ) {
        this.pinCityKey = pinCityKey;
    }
    public Long getPinCityKey() {
        return this.pinCityKey;
    }

    //--- DATABASE MAPPING : pin_state_key ( BIGINT ) 
    public void setPinStateKey( Long pinStateKey ) {
        this.pinStateKey = pinStateKey;
    }
    public Long getPinStateKey() {
        return this.pinStateKey;
    }

    //--- DATABASE MAPPING : pin_country_key ( BIGINT ) 
    public void setPinCountryKey( Long pinCountryKey ) {
        this.pinCountryKey = pinCountryKey;
    }
    public Long getPinCountryKey() {
        return this.pinCountryKey;
    }

    //--- DATABASE MAPPING : pin_remarks ( VARCHAR ) 
    public void setPinRemarks( String pinRemarks ) {
        this.pinRemarks = pinRemarks;
    }
    public String getPinRemarks() {
        return this.pinRemarks;
    }
    
    public Long getPinCreatorKey() {
		return pinCreatorKey;
	}
	public void setPinCreatorKey(Long pinCreatorKey) {
		this.pinCreatorKey = pinCreatorKey;
	}
	
	public String getPinPreviousStatus() {
		return pinPreviousStatus;
	}
	public void setPinPreviousStatus(String pinPreviousStatus) {
		this.pinPreviousStatus = pinPreviousStatus;
	}

	//--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    /*public void setListOfTIdEducationalInformation( List<TIdEducationalInformationEntity> listOfTIdEducationalInformation ) {
        this.listOfTIdEducationalInformation = listOfTIdEducationalInformation;
    }
    public List<TIdEducationalInformationEntity> getListOfTIdEducationalInformation() {
        return this.listOfTIdEducationalInformation;
    }*/

   /* public void setListOfTIdCommunicationInformation( List<TIdCommunicationInformationEntity> listOfTIdCommunicationInformation ) {
        this.listOfTIdCommunicationInformation = listOfTIdCommunicationInformation;
    }
    public List<TIdCommunicationInformationEntity> getListOfTIdCommunicationInformation() {
        return this.listOfTIdCommunicationInformation;
    }*/

    /*public void setListOfTIdExperienceInformation( List<TIdExperienceInformationEntity> listOfTIdExperienceInformation ) {
        this.listOfTIdExperienceInformation = listOfTIdExperienceInformation;
    }
    public List<TIdExperienceInformationEntity> getListOfTIdExperienceInformation() {
        return this.listOfTIdExperienceInformation;
    }

    public void setListOfTIdAdditionalInformation( List<TIdAdditionalInformationEntity> listOfTIdAdditionalInformation ) {
        this.listOfTIdAdditionalInformation = listOfTIdAdditionalInformation;
    }
    public List<TIdAdditionalInformationEntity> getListOfTIdAdditionalInformation() {
        return this.listOfTIdAdditionalInformation;
    }

    public void setListOfTIdAwardsInformation( List<TIdAwardsInformationEntity> listOfTIdAwardsInformation ) {
        this.listOfTIdAwardsInformation = listOfTIdAwardsInformation;
    }
    public List<TIdAwardsInformationEntity> getListOfTIdAwardsInformation() {
        return this.listOfTIdAwardsInformation;
    }

    public void setListOfTIdLanguageInformation( List<TIdLanguageInformationEntity> listOfTIdLanguageInformation ) {
        this.listOfTIdLanguageInformation = listOfTIdLanguageInformation;
    }
    public List<TIdLanguageInformationEntity> getListOfTIdLanguageInformation() {
        return this.listOfTIdLanguageInformation;
    }

    public void setListOfTIdProjectsInformation( List<TIdProjectsInformationEntity> listOfTIdProjectsInformation ) {
        this.listOfTIdProjectsInformation = listOfTIdProjectsInformation;
    }
    public List<TIdProjectsInformationEntity> getListOfTIdProjectsInformation() {
        return this.listOfTIdProjectsInformation;
    }

    public void setListOfTIdVisitInformation( List<TIdVisitInformationEntity> listOfTIdVisitInformation ) {
        this.listOfTIdVisitInformation = listOfTIdVisitInformation;
    }
    public List<TIdVisitInformationEntity> getListOfTIdVisitInformation() {
        return this.listOfTIdVisitInformation;
    }

    public void setListOfTIdMiscInformation( List<TIdMiscInformationEntity> listOfTIdMiscInformation ) {
        this.listOfTIdMiscInformation = listOfTIdMiscInformation;
    }
    public List<TIdMiscInformationEntity> getListOfTIdMiscInformation() {
        return this.listOfTIdMiscInformation;
    }

    public void setListOfTIdSocialMediaInformation( List<TIdSocialMediaInformationEntity> listOfTIdSocialMediaInformation ) {
        this.listOfTIdSocialMediaInformation = listOfTIdSocialMediaInformation;
    }
    public List<TIdSocialMediaInformationEntity> getListOfTIdSocialMediaInformation() {
        return this.listOfTIdSocialMediaInformation;
    }*/


    public Date getModifiedOn() {
		return modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getPinDobStr() {
		return pinDobStr;
	}
	public void setPinDobStr(String pinDobStr) {
		this.pinDobStr = pinDobStr;
	}
	
	public Date getPinDoa() {
		return pinDoa;
	}
	public void setPinDoa(Date pinDoa) {
		this.pinDoa = pinDoa;
	}
	
	

	public Long getPinPercentage() {
		return pinPercentage;
	}

	public void setPinPercentage(Long pinPercentage) {
		this.pinPercentage = pinPercentage;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pinKey);
        sb.append("]:"); 
        sb.append(pinTitle);
        sb.append("|");
        sb.append(pinFirstName);
        sb.append("|");
        sb.append(pinLastName);
        sb.append("|");
        sb.append(pinNickName);
        sb.append("|");
        sb.append(pinGender);
        sb.append("|");
        sb.append(pinNationalityKey);
        sb.append("|");
        sb.append(pinDob);
        sb.append("|");
        sb.append(pinEmail);
        sb.append("|");
        sb.append(pinAddress);
        sb.append("|");
        sb.append(pinCityKey);
        sb.append("|");
        sb.append(pinStateKey);
        sb.append("|");
        sb.append(pinCountryKey);
        sb.append("|");
        sb.append(pinRemarks);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(pinDobStr);
        sb.append("|");
        sb.append(pinPercentage);
        
        return sb.toString(); 
    } 

}
