
/*
 * Created on 22 Feb 2017 ( Time 14:31:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Persistent class for entity stored in table "t_id_recreation_info_view"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_recreation_info_view")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdRecreationInfoViewEntity.countAll", query="SELECT COUNT(x) FROM TIdRecreationInfoViewEntity x" )
} )
public class TIdRecreationInfoViewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------   
    @Id
    @Column(name="rei_key", nullable=false)
		
     private Long       key       ;

    @Column(name="rei_pin_key", nullable=false)
		
     private Long       reiPinKey    ;

    @Column(name="rei_rm_key")
		
     private Long       reiRmKey     ;

    @Column(name="rei_rm_others", length=75)
		
     private String     reiRmOthers  ;

    @Column(name="profile_key", nullable=false)
		
     private Long       profileKey   ;

    @Column(name="lock_key", nullable=false)
				@Version
		
     private Long       lockKey      ;

    @Column(name="active_status", nullable=false, length=75)
		
     private String     activeStatus ;

    @Column(name="pin_key")
		
     private Long       pinKey       ;

    @Column(name="name", length=75)
		
     private String     name         ;

    @Column(name="rm_logo", length=200)
	
    private String     rmLogo       ;
    
    @Column(name = "rei_rm_status")
    private String     reiRmStatus;
    
    
    @Column(name = "rei_created_by",length=20)
    private Long     reiCreatedBy;
       
    
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

	public String getReiRmStatus() {
		return reiRmStatus;
	}

	public void setReiRmStatus(String reiRmStatus) {
		this.reiRmStatus = reiRmStatus;
	}

	//----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdRecreationInfoViewEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : rei_key ( BIGINT ) 
    public void setKey( Long key ) {
        this.key = key;
    }
    public Long getKey() {
        return this.key;
    }

    //--- DATABASE MAPPING : rei_pin_key ( BIGINT ) 
    public void setReiPinKey( Long reiPinKey ) {
        this.reiPinKey = reiPinKey;
    }
    public Long getReiPinKey() {
        return this.reiPinKey;
    }

    //--- DATABASE MAPPING : rei_rm_key ( BIGINT ) 
    public void setReiRmKey( Long reiRmKey ) {
        this.reiRmKey = reiRmKey;
    }
    public Long getReiRmKey() {
        return this.reiRmKey;
    }

    //--- DATABASE MAPPING : rei_rm_others ( VARCHAR ) 
    public void setReiRmOthers( String reiRmOthers ) {
        this.reiRmOthers = reiRmOthers;
    }
    public String getReiRmOthers() {
        return this.reiRmOthers;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : active_status ( VARCHAR ) 
    public void setActiveStatus( String activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public String getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : pin_key ( BIGINT ) 
    public void setPinKey( Long pinKey ) {
        this.pinKey = pinKey;
    }
    public Long getPinKey() {
        return this.pinKey;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public String getRmLogo() {
		return rmLogo;
	}

	public void setRmLogo(String rmLogo) {
		this.rmLogo = rmLogo;
	}
	
	public Long getReiCreatedBy() {
		return reiCreatedBy;
	}

	public void setReiCreatedBy(Long reiCreatedBy) {
		this.reiCreatedBy = reiCreatedBy;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(key);
        sb.append("|");
        sb.append(reiPinKey);
        sb.append("|");
        sb.append(reiRmKey);
        sb.append("|");
        sb.append(reiRmOthers);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(pinKey);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(reiRmStatus);
        sb.append("|");
        sb.append(reiCreatedBy);
        return sb.toString(); 
    } 

}
