/*
 * Created on 13 Nov 2016 ( Time 16:25:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.id.wasta.util.action.CommonConstants;

/**
 * Persistent class for entity stored in table "T_ID_TABLE_AUDIT_LOG"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_table_audit_log" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdTableAuditLogEntity.countAll", query="SELECT COUNT(x) FROM TIdTableAuditLogEntity x" )
} )
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIdTableAuditLogEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="taudit_key", nullable=false)
    private Long       tauditKey    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="taudit_table_name", length=225)
    private String     tauditTableName ;

    @Column(name="taudit_record_type", length=3)
    private String     tauditRecordType ;

    @Column(name="taudit_key_name_1", length=720)
    private String     tauditKeyName1 ;

    @Column(name="taudit_key_value_1")
    private Long       tauditKeyValue1 ;

    @Column(name="taudit_key_name_2", length=720)
    private String     tauditKeyName2 ;

    @Column(name="taudit_key_value_2")
    private Long       tauditKeyValue2 ;

    @Column(name="taudit_key_name_3", length=720)
    private String     tauditKeyName3 ;

    @Column(name="taudit_key_value_3")
    private Long       tauditKeyValue3 ;

    @Column(name="taudit_key_name_4", length=720)
    private String     tauditKeyName4 ;

    @Column(name="taudit_key_value_4")
    private Long       tauditKeyValue4 ;

    @Column(name="taudit_key_name_5", length=720)
    private String     tauditKeyName5 ;

    @Column(name="taudit_key_value_5")
    private Long       tauditKeyValue5 ;

    @Column(name="taudit_action_by", nullable=false)
    private Long       tauditActionBy ;

    @Column(name="taudit_action_name", nullable=false, length=25)
     private String     tauditActionName ;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.DATE)
    @Column(name="taudit_action_on")
    private Date       tauditActionOn ;

    @Column(name="taudit_action_ip", length=720)
    private String     tauditActionIp ;

    @Column(name="taudit_notes", length=12000)
    private String     tauditNotes  ;
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone = CommonConstants.APP_TIME_ZONE)
    @Temporal(TemporalType.DATE)
    @Column(name="taudit_time_stamp", nullable=false)
    private Date       tauditTimeStamp ;

    @Column(name="taudit_lock_key", nullable=false)
    private Long       tauditLockKey ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdTableAuditLogEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTauditKey( Long tauditKey ) {
        this.tauditKey = tauditKey ;
    }
    public Long getTauditKey() {
        return this.tauditKey;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : taudit_table_name ( VARCHAR ) 
    public void setTauditTableName( String tauditTableName ) {
        this.tauditTableName = tauditTableName;
    }
    public String getTauditTableName() {
        return this.tauditTableName;
    }

    //--- DATABASE MAPPING : taudit_record_type ( VARCHAR ) 
    public void setTauditRecordType( String tauditRecordType ) {
        this.tauditRecordType = tauditRecordType;
    }
    public String getTauditRecordType() {
        return this.tauditRecordType;
    }

    //--- DATABASE MAPPING : taudit_key_name_1 ( VARCHAR ) 
    public void setTauditKeyName1( String tauditKeyName1 ) {
        this.tauditKeyName1 = tauditKeyName1;
    }
    public String getTauditKeyName1() {
        return this.tauditKeyName1;
    }

    //--- DATABASE MAPPING : taudit_key_value_1 ( BIGINT ) 
    public void setTauditKeyValue1( Long tauditKeyValue1 ) {
        this.tauditKeyValue1 = tauditKeyValue1;
    }
    public Long getTauditKeyValue1() {
        return this.tauditKeyValue1;
    }

    //--- DATABASE MAPPING : taudit_key_name_2 ( VARCHAR ) 
    public void setTauditKeyName2( String tauditKeyName2 ) {
        this.tauditKeyName2 = tauditKeyName2;
    }
    public String getTauditKeyName2() {
        return this.tauditKeyName2;
    }

    //--- DATABASE MAPPING : taudit_key_value_2 ( BIGINT ) 
    public void setTauditKeyValue2( Long tauditKeyValue2 ) {
        this.tauditKeyValue2 = tauditKeyValue2;
    }
    public Long getTauditKeyValue2() {
        return this.tauditKeyValue2;
    }

    //--- DATABASE MAPPING : taudit_key_name_3 ( VARCHAR ) 
    public void setTauditKeyName3( String tauditKeyName3 ) {
        this.tauditKeyName3 = tauditKeyName3;
    }
    public String getTauditKeyName3() {
        return this.tauditKeyName3;
    }

    //--- DATABASE MAPPING : taudit_key_value_3 ( BIGINT ) 
    public void setTauditKeyValue3( Long tauditKeyValue3 ) {
        this.tauditKeyValue3 = tauditKeyValue3;
    }
    public Long getTauditKeyValue3() {
        return this.tauditKeyValue3;
    }

    //--- DATABASE MAPPING : taudit_key_name_4 ( VARCHAR ) 
    public void setTauditKeyName4( String tauditKeyName4 ) {
        this.tauditKeyName4 = tauditKeyName4;
    }
    public String getTauditKeyName4() {
        return this.tauditKeyName4;
    }

    //--- DATABASE MAPPING : taudit_key_value_4 ( BIGINT ) 
    public void setTauditKeyValue4( Long tauditKeyValue4 ) {
        this.tauditKeyValue4 = tauditKeyValue4;
    }
    public Long getTauditKeyValue4() {
        return this.tauditKeyValue4;
    }

    //--- DATABASE MAPPING : taudit_key_name_5 ( VARCHAR ) 
    public void setTauditKeyName5( String tauditKeyName5 ) {
        this.tauditKeyName5 = tauditKeyName5;
    }
    public String getTauditKeyName5() {
        return this.tauditKeyName5;
    }

    //--- DATABASE MAPPING : taudit_key_value_5 ( BIGINT ) 
    public void setTauditKeyValue5( Long tauditKeyValue5 ) {
        this.tauditKeyValue5 = tauditKeyValue5;
    }
    public Long getTauditKeyValue5() {
        return this.tauditKeyValue5;
    }

    //--- DATABASE MAPPING : taudit_action_by ( BIGINT ) 
    public void setTauditActionBy( Long tauditActionBy ) {
        this.tauditActionBy = tauditActionBy;
    }
    public Long getTauditActionBy() {
        return this.tauditActionBy;
    }

    //--- DATABASE MAPPING : taudit_action_name ( VARCHAR ) 
    public void setTauditActionName( String tauditActionName ) {
        this.tauditActionName = tauditActionName;
    }
    public String getTauditActionName() {
        return this.tauditActionName;
    }

    //--- DATABASE MAPPING : taudit_action_on ( TIMESTAMP ) 
    public void setTauditActionOn( Date tauditActionOn ) {
        this.tauditActionOn = tauditActionOn;
    }
    public Date getTauditActionOn() {
        return this.tauditActionOn;
    }

    //--- DATABASE MAPPING : taudit_action_ip ( VARCHAR ) 
    public void setTauditActionIp( String tauditActionIp ) {
        this.tauditActionIp = tauditActionIp;
    }
    public String getTauditActionIp() {
        return this.tauditActionIp;
    }

    //--- DATABASE MAPPING : taudit_notes ( VARCHAR ) 
    public void setTauditNotes( String tauditNotes ) {
        this.tauditNotes = tauditNotes;
    }
    public String getTauditNotes() {
        return this.tauditNotes;
    }

    //--- DATABASE MAPPING : taudit_time_stamp ( TIMESTAMP ) 
    public void setTauditTimeStamp( Date tauditTimeStamp ) {
        this.tauditTimeStamp = tauditTimeStamp;
    }
    public Date getTauditTimeStamp() {
        return this.tauditTimeStamp;
    }

    //--- DATABASE MAPPING : taudit_lock_key ( BIGINT ) 
    public void setTauditLockKey( Long tauditLockKey ) {
        this.tauditLockKey = tauditLockKey;
    }
    public Long getTauditLockKey() {
        return this.tauditLockKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(tauditKey);
        sb.append("]:"); 
        sb.append(tauditTableName);
        sb.append("|");
        sb.append(tauditRecordType);
        sb.append("|");
        sb.append(tauditKeyName1);
        sb.append("|");
        sb.append(tauditKeyValue1);
        sb.append("|");
        sb.append(tauditKeyName2);
        sb.append("|");
        sb.append(tauditKeyValue2);
        sb.append("|");
        sb.append(tauditKeyName3);
        sb.append("|");
        sb.append(tauditKeyValue3);
        sb.append("|");
        sb.append(tauditKeyName4);
        sb.append("|");
        sb.append(tauditKeyValue4);
        sb.append("|");
        sb.append(tauditKeyName5);
        sb.append("|");
        sb.append(tauditKeyValue5);
        sb.append("|");
        sb.append(tauditActionBy);
        sb.append("|");
        sb.append(tauditActionName);
        sb.append("|");
        sb.append(tauditActionOn);
        sb.append("|");
        sb.append(tauditActionIp);
        sb.append("|");
        sb.append(tauditNotes);
        sb.append("|");
        sb.append(tauditTimeStamp);
        sb.append("|");
        sb.append(tauditLockKey);
        return sb.toString(); 
    } 

}
