/*
 * Created on 24 Dec 2018 ( Time 11:50:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.id.wasta.bean.jpa;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "t_id_user_master_list_view"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_id_user_master_list_view" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TIdUserMasterListViewEntity.countAll", query="SELECT COUNT(x) FROM TIdUserMasterListViewEntity x" )
} )
public class TIdUserMasterListViewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Id
    @Column(name="user_key", nullable=false)
    private Long       userKey      ;

    @Column(name="user_code", nullable=false, length=50)
    private String     userCode     ;

    @Column(name="user_first_name", length=75)
    private String     userFirstName ;

    @Column(name="user_middle_name", length=75)
    private String     userMiddleName ;

    @Column(name="user_last_name", nullable=false, length=75)
    private String     userLastName ;

    @Column(name="user_display_name", length=240)
    private String     userDisplayName ;

    @Column(name="user_company_key")
    private Long       userCompanyKey ;

    @Column(name="user_address_link")
    private Long       userAddressLink ;

    @Column(name="user_default_profile_key", nullable=false)
    private Long       userDefaultProfileKey ;

    @Column(name="user_verification_code")
    private Long       userVerificationCode ;

    @Column(name="active_status", nullable=false)
    private Long       activeStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="user_active_from")
    private Date       userActiveFrom ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="user_active_to")
    private Date       userActiveTo ;

    @Column(name="user_password", nullable=false, length=75)
    private String     userPassword ;

    @Column(name="user_pin_key", nullable=false)
    private Long       userPinKey   ;

    @Column(name="user_lock_count", nullable=false)
    private Long       userLockCount ;

    @Column(name="profile_key", nullable=false)
    private Long       profileKey   ;

    @Column(name="lock_key", nullable=false)
    private Long       lockKey      ;

    @Column(name="uprl_user_role_key")
    private Long       uprlUserRoleKey ;

    @Column(name="name", length=240)
    private String     name         ;

    @Column(name="code", length=75)
    private String     code         ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TIdUserMasterListViewEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : user_key ( BIGINT ) 
    public void setUserKey( Long userKey ) {
        this.userKey = userKey;
    }
    public Long getUserKey() {
        return this.userKey;
    }

    //--- DATABASE MAPPING : user_code ( VARCHAR ) 
    public void setUserCode( String userCode ) {
        this.userCode = userCode;
    }
    public String getUserCode() {
        return this.userCode;
    }

    //--- DATABASE MAPPING : user_first_name ( VARCHAR ) 
    public void setUserFirstName( String userFirstName ) {
        this.userFirstName = userFirstName;
    }
    public String getUserFirstName() {
        return this.userFirstName;
    }

    //--- DATABASE MAPPING : user_middle_name ( VARCHAR ) 
    public void setUserMiddleName( String userMiddleName ) {
        this.userMiddleName = userMiddleName;
    }
    public String getUserMiddleName() {
        return this.userMiddleName;
    }

    //--- DATABASE MAPPING : user_last_name ( VARCHAR ) 
    public void setUserLastName( String userLastName ) {
        this.userLastName = userLastName;
    }
    public String getUserLastName() {
        return this.userLastName;
    }

    //--- DATABASE MAPPING : user_display_name ( VARCHAR ) 
    public void setUserDisplayName( String userDisplayName ) {
        this.userDisplayName = userDisplayName;
    }
    public String getUserDisplayName() {
        return this.userDisplayName;
    }

    //--- DATABASE MAPPING : user_company_key ( BIGINT ) 
    public void setUserCompanyKey( Long userCompanyKey ) {
        this.userCompanyKey = userCompanyKey;
    }
    public Long getUserCompanyKey() {
        return this.userCompanyKey;
    }

    //--- DATABASE MAPPING : user_address_link ( BIGINT ) 
    public void setUserAddressLink( Long userAddressLink ) {
        this.userAddressLink = userAddressLink;
    }
    public Long getUserAddressLink() {
        return this.userAddressLink;
    }

    //--- DATABASE MAPPING : user_default_profile_key ( BIGINT ) 
    public void setUserDefaultProfileKey( Long userDefaultProfileKey ) {
        this.userDefaultProfileKey = userDefaultProfileKey;
    }
    public Long getUserDefaultProfileKey() {
        return this.userDefaultProfileKey;
    }

    //--- DATABASE MAPPING : user_verification_code ( BIGINT ) 
    public void setUserVerificationCode( Long userVerificationCode ) {
        this.userVerificationCode = userVerificationCode;
    }
    public Long getUserVerificationCode() {
        return this.userVerificationCode;
    }

    //--- DATABASE MAPPING : active_status ( BIGINT ) 
    public void setActiveStatus( Long activeStatus ) {
        this.activeStatus = activeStatus;
    }
    public Long getActiveStatus() {
        return this.activeStatus;
    }

    //--- DATABASE MAPPING : user_active_from ( DATETIME ) 
    public void setUserActiveFrom( Date userActiveFrom ) {
        this.userActiveFrom = userActiveFrom;
    }
    public Date getUserActiveFrom() {
        return this.userActiveFrom;
    }

    //--- DATABASE MAPPING : user_active_to ( DATETIME ) 
    public void setUserActiveTo( Date userActiveTo ) {
        this.userActiveTo = userActiveTo;
    }
    public Date getUserActiveTo() {
        return this.userActiveTo;
    }

    //--- DATABASE MAPPING : user_password ( VARCHAR ) 
    public void setUserPassword( String userPassword ) {
        this.userPassword = userPassword;
    }
    public String getUserPassword() {
        return this.userPassword;
    }

    //--- DATABASE MAPPING : user_pin_key ( BIGINT ) 
    public void setUserPinKey( Long userPinKey ) {
        this.userPinKey = userPinKey;
    }
    public Long getUserPinKey() {
        return this.userPinKey;
    }

    //--- DATABASE MAPPING : user_lock_count ( BIGINT ) 
    public void setUserLockCount( Long userLockCount ) {
        this.userLockCount = userLockCount;
    }
    public Long getUserLockCount() {
        return this.userLockCount;
    }

    //--- DATABASE MAPPING : profile_key ( BIGINT ) 
    public void setProfileKey( Long profileKey ) {
        this.profileKey = profileKey;
    }
    public Long getProfileKey() {
        return this.profileKey;
    }

    //--- DATABASE MAPPING : lock_key ( BIGINT ) 
    public void setLockKey( Long lockKey ) {
        this.lockKey = lockKey;
    }
    public Long getLockKey() {
        return this.lockKey;
    }

    //--- DATABASE MAPPING : uprl_user_role_key ( BIGINT ) 
    public void setUprlUserRoleKey( Long uprlUserRoleKey ) {
        this.uprlUserRoleKey = uprlUserRoleKey;
    }
    public Long getUprlUserRoleKey() {
        return this.uprlUserRoleKey;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(userKey);
        sb.append("|");
        sb.append(userCode);
        sb.append("|");
        sb.append(userFirstName);
        sb.append("|");
        sb.append(userMiddleName);
        sb.append("|");
        sb.append(userLastName);
        sb.append("|");
        sb.append(userDisplayName);
        sb.append("|");
        sb.append(userCompanyKey);
        sb.append("|");
        sb.append(userAddressLink);
        sb.append("|");
        sb.append(userDefaultProfileKey);
        sb.append("|");
        sb.append(userVerificationCode);
        sb.append("|");
        sb.append(activeStatus);
        sb.append("|");
        sb.append(userActiveFrom);
        sb.append("|");
        sb.append(userActiveTo);
        sb.append("|");
        sb.append(userPassword);
        sb.append("|");
        sb.append(userPinKey);
        sb.append("|");
        sb.append(userLockCount);
        sb.append("|");
        sb.append(profileKey);
        sb.append("|");
        sb.append(lockKey);
        sb.append("|");
        sb.append(uprlUserRoleKey);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(code);
        return sb.toString(); 
    } 

}
